// KPSS tarzı soru bankası (son 10 yılın konu dağılımına göre hazırlanmış özgün sorular) ve bilgi kartları
window.Q = [
// ---------- TÜRKÇE ----------
{ s: "tr", t: "Ses Bilgisi", q: "Aşağıdaki sözcüklerin hangisi büyük ünlü uyumuna uyar?", o: ["kitap", "otobüs", "kardeş", "yağmurluk", "anne"], a: 3, e: "“Yağmurluk” sözcüğündeki a, u, u ünlülerinin hepsi kalındır. Diğerlerinde kalın ve ince ünlüler karışıktır." },
{ s: "tr", t: "Ses Bilgisi", q: "Aşağıdakilerin hangisinde ünsüz benzeşmesi vardır?", o: ["kitabı", "ağzı", "sokakta", "başlıyor", "hakkı"], a: 2, e: "sokak + da → sokakta: sert ünsüz k'den sonra gelen d, t'ye dönüşmüştür. Kitabı yumuşama, ağzı ünlü düşmesi, başlıyor ünlü daralması, hakkı ünsüz türemesidir." },
{ s: "tr", t: "Ses Bilgisi", q: "Aşağıdakilerin hangisinde ünsüz yumuşaması vardır?", o: ["topu", "dolabı", "saçı", "Ahmet'e", "hakkı"], a: 1, e: "dolap + ı → dolabı: p, b'ye dönüşmüştür. Tek heceli “top, saç”ta yumuşama olmaz; özel adlarda yumuşama yazıda gösterilmez." },
{ s: "tr", t: "Ses Bilgisi", q: "Aşağıdakilerin hangisinde ünlü düşmesi vardır?", o: ["burnu", "kitabı", "kapıcı", "okuyor", "sessiz"], a: 0, e: "burun + u → burnu: ikinci hecedeki u ünlüsü düşmüştür." },
{ s: "tr", t: "Yazım Kuralları", q: "Aşağıdaki cümlelerin hangisinde “de” bağlacının yazımıyla ilgili bir yanlışlık yapılmıştır?", o: ["Sen de bizimle gel.", "Evde kimse yoktu.", "Bu konuyu o da biliyor.", "Kitabı masada bıraktım.", "Bende seninle gelmek istiyorum."], a: 4, e: "“Ben de” bağlaçtır ve ayrı yazılmalıdır. Çıkarıldığında cümle anlamını korur: “Ben seninle gelmek istiyorum.”" },
{ s: "tr", t: "Yazım Kuralları", q: "Aşağıdaki cümlelerin hangisinde “ki”nin yazımı yanlıştır?", o: ["Duydum ki gitmişsin.", "Evdeki eşyalar taşındı.", "Sanki hiçbir şey olmamış gibi davrandı.", "Oysa ki bana söz vermiştin.", "Belki yarın gelir."], a: 3, e: "“Oysaki” kalıplaşmış olduğu için bitişik yazılır: belki, çünkü, sanki, oysaki, mademki, hâlbuki, meğerki." },
{ s: "tr", t: "Yazım Kuralları", q: "Aşağıdakilerin hangisinde sayıların yazımı yanlıştır?", o: ["On beş gün sonra döndü.", "Yarışmada 3'üncü oldu.", "Sınıfın 3.'üncüsü oldu.", "1990'lı yıllarda doğdu.", "Tren saat 15.30'da kalkacak."], a: 2, e: "Rakamla yazılan sıra sayısında nokta ya da kesme ile ek birlikte kullanılmaz: “3.” veya “3'üncü” yazılır." },
{ s: "tr", t: "Yazım Kuralları", q: "Aşağıdakilerin hangisinde büyük harflerin kullanımıyla ilgili bir yanlışlık vardır?", o: ["Van Gölü'nün kıyısında yürüdük.", "Türk Dil Kurumunun yayınlarını inceledi.", "Evleri Ankara caddesi üzerindeydi.", "Nutuk'u yeniden okudum.", "Toplantı pazartesi günü yapılacak."], a: 2, e: "Cadde, sokak adlarında her sözcük büyük harfle başlar: Ankara Caddesi. Belirli tarih bildirmeyen gün adları küçük yazılır." },
{ s: "tr", t: "Noktalama İşaretleri", q: "Aşağıdakilerin hangisinde kesme işareti yanlış kullanılmıştır?", o: ["Ankara'ya yarın gideceğiz.", "Ayşe'nin kitabını getirdim.", "Türk Dil Kurumu'nun sözlüğünü aldım.", "1923'te Cumhuriyet ilan edildi.", "TBMM'ye yeni bir teklif sunuldu."], a: 2, e: "Kurum, kuruluş adlarına gelen ekler kesmeyle ayrılmaz: “Türk Dil Kurumunun”. Kısaltmalarda ise ayrılır: TBMM'ye." },
{ s: "tr", t: "Cümlenin Ögeleri", q: "“Dün akşam arkadaşlarımla sinemaya gittik.” cümlesinin ögeleri sırasıyla hangi seçenekte verilmiştir?", o: ["Zarf tümleci – zarf tümleci – dolaylı tümleç – yüklem", "Özne – zarf tümleci – dolaylı tümleç – yüklem", "Zarf tümleci – dolaylı tümleç – nesne – yüklem", "Zarf tümleci – nesne – dolaylı tümleç – yüklem", "Özne – dolaylı tümleç – zarf tümleci – yüklem"], a: 0, e: "Ne zaman? Dün akşam (ZT). Kiminle? Arkadaşlarımla (ZT). Nereye? Sinemaya (DT). Gittik (yüklem). Özne gizlidir (biz)." },
{ s: "tr", t: "Anlatım Bozuklukları", q: "Aşağıdaki cümlelerin hangisinde gereksiz sözcük kullanımından kaynaklanan bir anlatım bozukluğu vardır?", o: ["Toplantıya yaklaşık yüz kadar kişi katıldı.", "Yarın erkenden yola çıkacağız.", "Bu kitabı herkese öneriyorum.", "Hava birden soğudu.", "Sınav sonuçları açıklandı."], a: 0, e: "“Yaklaşık” ve “kadar” aynı anlamı verir; biri atılmalıdır." },
{ s: "tr", t: "Anlatım Bozuklukları", q: "Aşağıdaki cümlelerin hangisinde anlamca çelişen sözcüklerin kullanılmasından kaynaklanan bir anlatım bozukluğu vardır?", o: ["Proje zamanında teslim edildi.", "Bu işi mutlaka bitirmiş olabilir.", "Kardeşim her sabah koşuya çıkar.", "Kitabın ikinci baskısı yapıldı.", "Misafirler akşama doğru geldi."], a: 1, e: "“Mutlaka” kesinlik, “olabilir” olasılık bildirir. İkisi aynı yargıda kullanılamaz." },
{ s: "tr", t: "Sözcükte ve Cümlede Anlam", q: "Aşağıdaki cümlelerin hangisinde “sert” sözcüğü mecaz anlamda kullanılmıştır?", o: ["Sert zeminde yürümek zordu.", "Kaya o kadar sertti ki delinemedi.", "Babası sert bir mizaca sahipti.", "Cevizin sert kabuğunu kırdı.", "Bu yatak benim için çok sert."], a: 2, e: "“Sert mizaç” kişinin huyunu anlatır; sözcük gerçek anlamından uzaklaşmıştır." },
{ s: "tr", t: "Sözcükte ve Cümlede Anlam", q: "Aşağıdaki cümlelerden hangisi nesnel bir yargıdır?", o: ["Ankara, Türkiye'nin başkentidir.", "Bu film çok sıkıcıydı.", "En güzel mevsim sonbahardır.", "Romanın dili akıcı ve etkileyiciydi.", "Bu şarkı herkesi derinden etkiler."], a: 0, e: "Ankara'nın başkent olduğu kanıtlanabilir bir bilgidir; diğerleri kişiden kişiye değişen yargılardır." },
{ s: "tr", t: "Sözcükte ve Cümlede Anlam", q: "“Etekleri zil çalmak” deyiminin anlamı aşağıdakilerden hangisidir?", o: ["Çok sevinmek", "Çok korkmak", "Telaşlanmak", "Çok üzülmek", "Öfkelenmek"], a: 0, e: "“Etekleri zil çalmak”, çok sevinmek anlamındadır." },
{ s: "tr", t: "Paragraf", q: "“Okumak, yalnızca bilgi edinmenin değil, düşünmenin de yoludur. Bir kitabı bitirdiğimizde aklımızda kalan cümlelerden çok, o kitabın bizde uyandırdığı sorular önemlidir. Çünkü sorular bizi başka kitaplara, başka insanlara ve en önemlisi kendi düşüncelerimize götürür.” Bu paragrafta asıl anlatılmak istenen nedir?", o: ["Okumanın asıl kazancı, okurda düşünmeyi başlatan sorular uyandırmasıdır.", "Kitaplardaki bilgiler zamanla unutulur.", "Çok kitap okuyan kişi daha çok insan tanır.", "Okur, kitaplardaki cümleleri ezberlemelidir.", "Her kitap bir sonraki kitaba hazırlıktır."], a: 0, e: "Paragraf, okumanın değerini okurda uyandırdığı sorulara ve düşünmeye bağlar. Diğer seçenekler ya metinde yoktur ya da ayrıntıdır." },
{ s: "tr", t: "Paragraf", q: "“Kasabanın girişinde, yosun tutmuş taş duvarların arasından kıvrılarak inen dar bir yol vardı. Yolun iki yanındaki yaşlı çınarlar, öğle sıcağında bile serin, yeşil bir tünel oluşturuyordu. Uzaktan gelen su sesi, bu serinliğe hafif bir ürperti katıyordu.” Bu paragrafta hangi anlatım biçimi kullanılmıştır?", o: ["Betimleme", "Tartışma", "Açıklama", "Öyküleme", "Karşılaştırma"], a: 0, e: "Yer, görme ve işitme duyularına seslenen ayrıntılarla resmedilmiştir. Olay örgüsü yoktur; bu betimlemedir." },
{ s: "tr", t: "Paragraf", q: "“Türkiye'nin nüfusu 1927'deki ilk sayımda yaklaşık 13,6 milyondu. Bu sayı 2023'te 85 milyonu aştı.” Bu cümlelerde hangi düşünceyi geliştirme yolu kullanılmıştır?", o: ["Tanımlama", "Tanık gösterme", "Sayısal verilerden yararlanma", "Benzetme", "Örneklendirme"], a: 2, e: "Düşünce, yıllara ait nüfus rakamlarıyla desteklenmiştir." },
{ s: "tr", t: "Paragraf", q: "(I) Kahve, 16. yüzyılda Yemen'den İstanbul'a geldi. (II) Kısa sürede şehirde kahvehaneler açıldı. (III) Kahvehaneler; sohbetin, oyunun ve haberleşmenin merkezi oldu. (IV) Günümüzde çay, Türkiye'de en çok tüketilen içecektir. (V) Hatta bazı dönemlerde yönetim, buralarda yapılan konuşmalardan çekinerek kahvehaneleri kapattırdı. Numaralanmış cümlelerden hangisi düşüncenin akışını bozmaktadır?", o: ["I", "II", "III", "IV", "V"], a: 3, e: "Paragraf kahvenin ve kahvehanelerin tarihini anlatır. IV. cümle günümüzdeki çay tüketimine geçerek akışı bozar; V. cümle III'e bağlanır." },
{ s: "tr", t: "Sözcük Türleri ve Fiilimsiler", q: "Aşağıdaki cümlelerin hangisinde “hızlı” sözcüğü zarf olarak kullanılmıştır?", o: ["Hızlı tren istasyona girdi.", "Çocuk hızlı koşuyordu.", "Hızlılar yarışta öne geçti.", "Hızlı adımlarla yürüdü.", "Bu araba çok hızlı."], a: 1, e: "“Nasıl koşuyordu?” sorusunun cevabıdır ve fiili nitelemektedir." },
{ s: "tr", t: "Sözcük Türleri ve Fiilimsiler", q: "Aşağıdaki cümlelerin hangisinde isim-fiil vardır?", o: ["Gelen misafirleri kapıda karşıladı.", "Koşarak eve geldi.", "Kitap okumayı çok seviyor.", "Okunmuş kitapları rafa dizdi.", "Haberi görünce sevindi."], a: 2, e: "oku-ma: -ma isim-fiil ekidir. “Gelen, okunmuş” sıfat-fiil; “koşarak, görünce” zarf-fiildir." },
{ s: "tr", t: "Cümle Türleri", q: "Aşağıdaki cümlelerden hangisi devrik cümledir?", o: ["Gel buraya.", "Yarın okula gideceğim.", "Kitabını masaya bıraktı.", "Hava bugün çok soğuk.", "Kardeşim de bizimle geldi."], a: 0, e: "Yüklem (gel) cümlenin sonunda değil; bu nedenle devrik cümledir." },
{ s: "tr", t: "Cümle Türleri", q: "“Yağmur yağınca yollar çamur oldu.” cümlesi yapısına göre hangi türdedir?", o: ["Basit cümle", "Girişik birleşik cümle", "Sıralı cümle", "Bağlı cümle", "Şartlı birleşik cümle"], a: 1, e: "“Yağmur yağınca” zarf-fiil grubudur. Fiilimsi grubu içeren cümle girişik birleşik cümledir." },
{ s: "tr", t: "Sözel Mantık", q: "Ali, Berk, Can, Deniz ve Ece yan yana beş sandalyeye oturmuştur. Ali en soldadır, Can ortadaki sandalyededir. Ece, Deniz'in hemen sağında oturmaktadır. Buna göre soldan ikinci sandalyede kim oturmaktadır?", o: ["Ali", "Berk", "Can", "Deniz", "Ece"], a: 1, e: "Ali 1, Can 3. Deniz-Ece yan yana ve Ece sağda olduğundan yalnızca 4-5 kalır. Boş kalan 2. sandalye Berk'indir." },

// ---------- MATEMATİK ----------
{ s: "mat", t: "Temel Kavramlar", q: "1'den 20'ye kadar olan tam sayıların toplamı kaçtır?", o: ["190", "200", "210", "220", "230"], a: 2, e: "n(n+1)/2 = 20·21/2 = 210." },
{ s: "mat", t: "Temel Kavramlar", q: "Toplamları 78 olan ardışık üç çift sayının en büyüğü kaçtır?", o: ["22", "24", "26", "28", "30"], a: 2, e: "x + (x+2) + (x+4) = 78 → 3x = 72 → x = 24. En büyüğü 26." },
{ s: "mat", t: "Temel Kavramlar", q: "5, 9, 13, ..., 101 dizisinde kaç terim vardır?", o: ["23", "24", "25", "26", "27"], a: 2, e: "(101 − 5)/4 + 1 = 24 + 1 = 25." },
{ s: "mat", t: "Temel Kavramlar", q: "|x − 3| = 5 denklemini sağlayan x değerlerinin toplamı kaçtır?", o: ["−2", "2", "6", "8", "10"], a: 2, e: "x − 3 = 5 → x = 8; x − 3 = −5 → x = −2. Toplam 6." },
{ s: "mat", t: "Bölünebilme ve EBOB-EKOK", q: "a ve b birer rakam olmak üzere dört basamaklı 3a4b sayısı 5 ve 9 ile tam bölünebilmektedir. Buna göre a + b en fazla kaçtır?", o: ["2", "7", "9", "11", "13"], a: 3, e: "5 ile bölünme: b = 0 ya da 5. 9 ile bölünme: 3 + a + 4 + b = 7 + a + b, 9'un katı → a + b = 2 ya da 11. b = 5, a = 6 ile a + b = 11 olur." },
{ s: "mat", t: "Bölünebilme ve EBOB-EKOK", q: "24 ve 36 sayılarının EBOB'u ile EKOK'unun toplamı kaçtır?", o: ["60", "72", "84", "96", "108"], a: 2, e: "EBOB = 12, EKOK = 72. Toplam 84. Kontrol: 12 · 72 = 864 = 24 · 36." },
{ s: "mat", t: "Bölünebilme ve EBOB-EKOK", q: "72 sayısının kaç tane pozitif böleni vardır?", o: ["6", "8", "10", "12", "14"], a: 3, e: "72 = 2³ · 3² → (3+1)(2+1) = 12." },
{ s: "mat", t: "Rasyonel, Üslü ve Köklü Sayılar", q: "(2⁵ · 4²) / 8² işleminin sonucu kaçtır?", o: ["2", "4", "8", "16", "32"], a: 2, e: "2⁵ · 2⁴ / 2⁶ = 2⁹⁻⁶ = 2³ = 8." },
{ s: "mat", t: "Rasyonel, Üslü ve Köklü Sayılar", q: "√12 + √27 işleminin sonucu aşağıdakilerden hangisidir?", o: ["√39", "4√3", "5√3", "6√3", "13"], a: 2, e: "√12 = 2√3, √27 = 3√3. Toplam 5√3." },
{ s: "mat", t: "Rasyonel, Üslü ve Köklü Sayılar", q: "(1/2 + 1/3) : (1/6) işleminin sonucu kaçtır?", o: ["1", "2", "3", "5", "6"], a: 3, e: "1/2 + 1/3 = 5/6. (5/6) : (1/6) = 5." },
{ s: "mat", t: "Oran-Orantı ve Denklemler", q: "a/b = 3/5 ve a + b = 40 olduğuna göre b − a kaçtır?", o: ["5", "8", "10", "12", "15"], a: 2, e: "a = 3k, b = 5k → 8k = 40 → k = 5. b − a = 2k = 10." },
{ s: "mat", t: "Problemler", q: "Bir annenin yaşı kızının yaşının 3 katıdır. 12 yıl sonra annenin yaşı kızının yaşının 2 katı olacaktır. Annenin bugünkü yaşı kaçtır?", o: ["30", "33", "36", "39", "42"], a: 2, e: "Kız k, anne 3k. 3k + 12 = 2(k + 12) → k = 12. Anne 36 yaşındadır." },
{ s: "mat", t: "Problemler", q: "Fiyatı önce %20 artırılan, sonra %20 indirilen bir ürünün son fiyatı ilk fiyatına göre nasıl değişmiştir?", o: ["Değişmemiştir", "%4 artmıştır", "%4 azalmıştır", "%2 azalmıştır", "%8 azalmıştır"], a: 2, e: "100 → 120 → 96. Son fiyat ilk fiyattan %4 düşüktür." },
{ s: "mat", t: "Problemler", q: "Bir işi Ahmet tek başına 6 günde, Mehmet tek başına 12 günde bitirebiliyor. İkisi birlikte bu işi kaç günde bitirir?", o: ["3", "4", "5", "6", "9"], a: 1, e: "t = 6·12/(6+12) = 72/18 = 4 gün." },
{ s: "mat", t: "Problemler", q: "Aralarında 360 km bulunan iki araç, birbirlerine doğru saatte 50 km ve 70 km hızla aynı anda hareket ediyor. Kaç saat sonra karşılaşırlar?", o: ["2", "2,5", "3", "3,5", "4"], a: 2, e: "Karşılaşma süresi = 360/(50+70) = 3 saat." },
{ s: "mat", t: "Problemler", q: "Maliyeti 80 TL olan bir ürün %25 kârla satılırsa satış fiyatı kaç TL olur?", o: ["90", "95", "100", "105", "120"], a: 2, e: "Kâr maliyet üzerinden: 80 · 1,25 = 100 TL." },
{ s: "mat", t: "Kümeler", q: "30 kişilik bir sınıfta her öğrenci İngilizce ya da Almancadan en az birini konuşmaktadır. İngilizce konuşan 18, Almanca konuşan 15 öğrenci olduğuna göre her iki dili konuşan kaç öğrenci vardır?", o: ["3", "5", "6", "12", "15"], a: 0, e: "s(A∪B) = s(A) + s(B) − s(A∩B) → 30 = 18 + 15 − x → x = 3." },
{ s: "mat", t: "Kümeler", q: "5 elemanlı bir kümenin 2 elemanlı alt kümelerinin sayısı kaçtır?", o: ["5", "10", "15", "20", "25"], a: 1, e: "C(5,2) = 5·4/2 = 10." },
{ s: "mat", t: "Permütasyon ve Olasılık", q: "“KPSS” kelimesinin harfleri kullanılarak anlamlı ya da anlamsız 4 harfli kaç farklı kelime yazılabilir?", o: ["6", "12", "18", "24", "36"], a: 1, e: "4 harfin 2'si aynı (S): 4!/2! = 24/2 = 12." },
{ s: "mat", t: "Permütasyon ve Olasılık", q: "İki zar birlikte atıldığında üst yüzlerdeki sayıların toplamının 7 olma olasılığı kaçtır?", o: ["1/12", "1/9", "1/6", "5/36", "7/36"], a: 2, e: "Toplamı 7 olan 6 durum vardır: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). 6/36 = 1/6." },
{ s: "mat", t: "Geometri", q: "Bir üçgenin iç açıları 2, 3 ve 4 sayılarıyla orantılıdır. En büyük açı kaç derecedir?", o: ["60", "70", "80", "90", "100"], a: 2, e: "2k + 3k + 4k = 180 → k = 20. En büyük açı 4k = 80°." },
{ s: "mat", t: "Geometri", q: "Dik kenarları 6 cm ve 8 cm olan bir dik üçgenin alanı kaç cm²'dir?", o: ["14", "24", "28", "30", "48"], a: 1, e: "Dik üçgende alan = dik kenarların çarpımı / 2 = 6·8/2 = 24." },
{ s: "mat", t: "Geometri", q: "Düzgün altıgenin bir iç açısı kaç derecedir?", o: ["108", "120", "135", "140", "150"], a: 1, e: "(6 − 2)·180 / 6 = 720/6 = 120°." },
{ s: "mat", t: "Geometri", q: "Yarıçapı 3 cm olan dairenin alanı kaç cm²'dir? (π = 3 alınız.)", o: ["9", "18", "27", "36", "54"], a: 2, e: "πr² = 3 · 9 = 27." },
{ s: "mat", t: "Sayısal Mantık", q: "2, 6, 12, 20, 30, ? dizisinde soru işareti yerine hangi sayı gelmelidir?", o: ["36", "40", "42", "44", "48"], a: 2, e: "Terimler n(n+1): 1·2, 2·3, 3·4, 4·5, 5·6, 6·7 = 42. Farklar da 4, 6, 8, 10, 12 diye artar." },
{ s: "mat", t: "Sayısal Mantık", q: "3, 5, 9, 17, 33, ? dizisinde soru işareti yerine hangi sayı gelmelidir?", o: ["49", "57", "63", "65", "66"], a: 3, e: "Her terim bir öncekinin 2 katının 1 eksiği: 33·2 − 1 = 65." },

// ---------- TARİH ----------
{ s: "tar", t: "İslamiyet Öncesi Türk Tarihi", q: "“Türk” adıyla kurulan ilk Türk devleti aşağıdakilerden hangisidir?", o: ["Asya Hun Devleti", "Göktürk Devleti", "Uygur Devleti", "Hazar Devleti", "Avar Devleti"], a: 1, e: "Göktürkler, 552'de Bumin Kağan önderliğinde “Türk” adıyla kurulmuştur." },
{ s: "tar", t: "İslamiyet Öncesi Türk Tarihi", q: "Yerleşik hayata geçen ilk Türk devleti aşağıdakilerden hangisidir?", o: ["Göktürkler", "Uygurlar", "Asya Hunları", "Karluklar", "Kırgızlar"], a: 1, e: "Uygurlar Mani dinini benimseyince yerleşik hayata geçti; şehirler, tapınaklar, kendi alfabeleri ve matbaaları oldu." },
{ s: "tar", t: "İslamiyet Öncesi Türk Tarihi", q: "Orhun Yazıtları hangi Türk devletine aittir?", o: ["Asya Hun", "I. Göktürk", "II. Göktürk (Kutluk)", "Uygur", "Karahanlı"], a: 2, e: "Tonyukuk, Kül Tigin ve Bilge Kağan yazıtları II. Göktürk (Kutluk) Devleti döneminde dikilmiştir." },
{ s: "tar", t: "İslamiyet Öncesi Türk Tarihi", q: "Ordu teşkilatında onlu sistemi ilk kez uygulayan Türk hükümdarı kimdir?", o: ["Bumin Kağan", "Mete Han", "Attila", "Bilge Kağan", "Balamir"], a: 1, e: "Asya Hun hükümdarı Mete Han M.Ö. 209'da onlu sistemi kurmuştur. Bu tarih Türk Kara Kuvvetleri'nin kuruluşu kabul edilir." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "Türkçeyi resmî dil olarak kullanan ve Kutadgu Bilig'in yazıldığı Türk-İslam devleti hangisidir?", o: ["Gazneliler", "Karahanlılar", "Büyük Selçuklular", "Harzemşahlar", "Tolunoğulları"], a: 1, e: "Karahanlılar döneminde Yusuf Has Hacib Kutadgu Bilig'i yazmış, Türkçe resmî dil olarak kullanılmıştır." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "“Anadolu'nun kapılarının Türklere açıldığı” savaş hangisidir?", o: ["Dandanakan", "Pasinler", "Malazgirt", "Miryokefalon", "Kösedağ"], a: 2, e: "1071 Malazgirt Savaşı'nda Alparslan'ın Bizans'ı yenmesiyle Anadolu'ya Türk göçü hızlandı." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "Bizans'ın Anadolu'yu Türklerden geri alma ümidinin sona erdiği savaş hangisidir?", o: ["Malazgirt", "Miryokefalon", "Yassıçemen", "Kösedağ", "Pasinler"], a: 1, e: "1176 Miryokefalon Savaşı'yla Anadolu'nun Türk yurdu olduğu kesinleşti." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "Siyasetname adlı eserin yazarı kimdir?", o: ["Kaşgarlı Mahmud", "Yusuf Has Hacib", "Nizamülmülk", "Edip Ahmet Yükneki", "Farabi"], a: 2, e: "Büyük Selçuklu veziri Nizamülmülk Siyasetname'yi yazmış ve Nizamiye medreselerini kurmuştur." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Osmanlı Devleti'nin ilk büyük toprak kaybına uğradığı antlaşma hangisidir?", o: ["Zitvatorok", "Karlofça", "Pasarofça", "Belgrad", "Küçük Kaynarca"], a: 1, e: "1699 Karlofça Antlaşması ile Macaristan, Podolya, Mora gibi topraklar kaybedildi." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Kırım'ın bağımsız olduğu ve Osmanlı'nın ilk kez savaş tazminatı ödediği antlaşma hangisidir?", o: ["Yaş", "Ziştovi", "Küçük Kaynarca", "Edirne", "Bükreş"], a: 2, e: "1774 Küçük Kaynarca Antlaşması ile Kırım bağımsız oldu, Rusya Ortodoksların koruyuculuğunu üstlendi." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Lale Devri hangi antlaşmanın imzalanmasıyla başlamıştır?", o: ["Karlofça", "Pasarofça", "Belgrad", "Prut", "İstanbul"], a: 1, e: "1718 Pasarofça Antlaşması'ndan sonra 1730 Patrona Halil İsyanı'na kadar süren döneme Lale Devri denir." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "I. Meşrutiyet hangi padişah döneminde ilan edilmiştir?", o: ["II. Mahmut", "Abdülmecit", "Abdülaziz", "II. Abdülhamit", "V. Mehmet Reşat"], a: 3, e: "23 Aralık 1876'da II. Abdülhamit döneminde Kanun-i Esasi ilan edildi." },
{ s: "tar", t: "Osmanlı Kültür ve Medeniyeti", q: "Divan-ı Hümayun'da maliye işlerinden sorumlu olan üye hangisidir?", o: ["Kazasker", "Nişancı", "Defterdar", "Kaptan-ı Derya", "Şeyhülislam"], a: 2, e: "Defterdar maliyeden sorumluydu. Kazasker hukuk ve eğitimden, Nişancı tuğra ve tapudan sorumluydu." },
{ s: "tar", t: "Osmanlı Kültür ve Medeniyeti", q: "Osmanlı Devleti'nde askerlik yapmayan gayrimüslim erkeklerden alınan vergi hangisidir?", o: ["Öşür", "Cizye", "Avarız", "Çiftbozan", "Ağnam"], a: 1, e: "Cizye, askerlikle yükümlü olmayan gayrimüslim erkeklerden alınırdı." },
{ s: "tar", t: "Osmanlı Kültür ve Medeniyeti", q: "İbrahim Müteferrika'nın ilk Türk matbaasını kurduğu dönem hangisidir?", o: ["Kuruluş Dönemi", "Lale Devri", "Tanzimat Dönemi", "I. Meşrutiyet", "II. Meşrutiyet"], a: 1, e: "Matbaa 1727'de, Lale Devri'nde kuruldu." },
{ s: "tar", t: "Kurtuluş Savaşı: Hazırlık", q: "Mondros Ateşkes Antlaşması'nın hangi maddesi İtilaf devletlerine, güvenliklerini tehdit eden bir durumda herhangi bir stratejik noktayı işgal etme hakkı vermiştir?", o: ["5.", "7.", "16.", "20.", "24."], a: 1, e: "7. madde işgallere dayanak oluşturdu; 24. madde ise Vilayet-i Sitte'de Ermeni devleti kurulmasına zemin hazırladı." },
{ s: "tar", t: "Kurtuluş Savaşı: Hazırlık", q: "“Milletin istiklalini yine milletin azim ve kararı kurtaracaktır.” ifadesi hangi belgede yer almaktadır?", o: ["Havza Genelgesi", "Amasya Genelgesi", "Erzurum Kongresi kararları", "Sivas Kongresi kararları", "Misak-ı Milli"], a: 1, e: "22 Haziran 1919 Amasya Genelgesi, millî egemenliğe dayalı yeni bir yönetimin sinyalini veren ilk belgedir." },
{ s: "tar", t: "Kurtuluş Savaşı: Hazırlık", q: "Manda ve himayenin ilk kez reddedildiği kongre hangisidir?", o: ["Balıkesir", "Alaşehir", "Erzurum", "Sivas", "Nazilli"], a: 2, e: "Erzurum Kongresi'nde “Manda ve himaye kabul olunamaz” kararı alındı." },
{ s: "tar", t: "Kurtuluş Savaşı: Hazırlık", q: "Tüm yararlı cemiyetlerin “Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti” adı altında birleştirildiği kongre hangisidir?", o: ["Erzurum", "Sivas", "Balıkesir", "Alaşehir", "Pozantı"], a: 1, e: "Sivas Kongresi'nde cemiyetler birleştirildi ve Temsil Heyeti tüm yurdu temsil eder hâle geldi." },
{ s: "tar", t: "Kurtuluş Savaşı: Hazırlık", q: "Misak-ı Milli hangi meclis tarafından kabul edilmiştir?", o: ["TBMM", "Son Osmanlı Mebusan Meclisi", "Temsil Heyeti", "Heyet-i Temsiliye", "Kurucu Meclis"], a: 1, e: "Misak-ı Milli 28 Ocak 1920'de son Osmanlı Mebusan Meclisi'nde kabul edildi." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "TBMM'nin ilk askerî ve siyasi başarısı olan antlaşma hangisidir?", o: ["Gümrü", "Moskova", "Kars", "Ankara", "Mudanya"], a: 0, e: "3 Aralık 1920 Gümrü Antlaşması Ermenistan ile imzalandı; TBMM'nin ilk uluslararası antlaşmasıdır." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "Sakarya Meydan Muharebesi'nden sonra Mustafa Kemal'e TBMM tarafından ne verilmiştir?", o: ["Başkomutanlık yetkisi", "Gazi unvanı ve Mareşal rütbesi", "Cumhurbaşkanlığı", "Atatürk soyadı", "Kurmay subaylık"], a: 1, e: "Başkomutanlık yetkisi Sakarya'dan önce (Ağustos 1921) verilmişti. Zaferden sonra Gazi unvanı ve Mareşal rütbesi verildi." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "Tekalif-i Milliye Emirleri hangi savaştan önce yayımlanmıştır?", o: ["I. İnönü", "II. İnönü", "Kütahya-Eskişehir", "Sakarya", "Büyük Taarruz"], a: 3, e: "Kütahya-Eskişehir yenilgisinden sonra, Sakarya öncesinde ordunun ihtiyaçları için yayımlandı (Ağustos 1921)." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "Doğu Trakya'nın savaş yapılmadan kurtarıldığı belge hangisidir?", o: ["Lozan Barış Antlaşması", "Mudanya Ateşkes Antlaşması", "Ankara Antlaşması", "Kars Antlaşması", "Londra Konferansı"], a: 1, e: "11 Ekim 1922 Mudanya Ateşkesi ile Doğu Trakya ve İstanbul savaşmadan alındı." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Aşağıdakilerden hangisi 3 Mart 1924'te gerçekleşmemiştir?", o: ["Halifeliğin kaldırılması", "Tevhid-i Tedrisat Kanunu", "Şer'iye ve Evkaf Vekâletinin kaldırılması", "Erkân-ı Harbiye Vekâletinin kaldırılması", "Saltanatın kaldırılması"], a: 4, e: "Saltanat 1 Kasım 1922'de kaldırıldı. Diğer dördü 3 Mart 1924'te gerçekleşti." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Aşağıdakilerden hangisi toplumsal alanda yapılan inkılaplardandır?", o: ["Türk Medeni Kanunu'nun kabulü", "Harf İnkılabı", "Soyadı Kanunu", "Saltanatın kaldırılması", "Aşar vergisinin kaldırılması"], a: 2, e: "Soyadı Kanunu (1934) toplumsal alandadır. Medeni Kanun hukuk, Harf İnkılabı eğitim-kültür, saltanat siyasi, aşar ekonomi alanındadır." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Lakap ve unvanların (ağa, hacı, hoca, paşa vb.) kaldırılması öncelikle hangi ilkeyle ilgilidir?", o: ["Devletçilik", "Laiklik", "Halkçılık", "İnkılapçılık", "Milliyetçilik"], a: 2, e: "Halkçılık, sınıf ayrıcalıklarını reddeder ve toplumda eşitliği esas alır." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Türk kadını milletvekili seçme ve seçilme hakkını hangi yıl elde etmiştir?", o: ["1926", "1930", "1933", "1934", "1937"], a: 3, e: "5 Aralık 1934. Belediye seçimlerinde 1930'da, muhtarlıkta 1933'te hak tanınmıştı." },
{ s: "tar", t: "Atatürk Dönemi Dış Politika", q: "Boğazlar üzerinde tam Türk egemenliğini sağlayan sözleşme hangisidir?", o: ["Lozan", "Montrö", "Sadabat Paktı", "Balkan Antantı", "Ankara Antlaşması"], a: 1, e: "1936 Montrö Boğazlar Sözleşmesi ile Boğazlar Komisyonu kaldırıldı, egemenlik Türkiye'ye geçti." },
{ s: "tar", t: "Atatürk Dönemi Dış Politika", q: "Türkiye Milletler Cemiyeti'ne hangi yıl üye olmuştur?", o: ["1923", "1926", "1930", "1932", "1936"], a: 3, e: "Türkiye 1932'de davet üzerine Milletler Cemiyeti'ne üye oldu." },
{ s: "tar", t: "Çağdaş Türk ve Dünya Tarihi", q: "Türkiye'nin Kore Savaşı'na asker göndermesinin en önemli sonucu aşağıdakilerden hangisidir?", o: ["BM'ye üye olması", "NATO'ya üye olmasının kolaylaşması", "Marshall yardımı alması", "Balkan Paktı'nı kurması", "Avrupa Konseyi'ne girmesi"], a: 1, e: "Kore'ye asker gönderilmesi (1950) Batı ile yakınlaşmayı sağladı; Türkiye 1952'de NATO'ya üye oldu." },

// ---------- COĞRAFYA ----------
{ s: "cog", t: "Coğrafi Konum", q: "Türkiye'nin en doğusu ile en batısı arasındaki yerel saat farkı kaç dakikadır?", o: ["60", "72", "76", "80", "84"], a: 2, e: "26°–45° Doğu boylamları: 19 boylam × 4 dk = 76 dk." },
{ s: "cog", t: "Coğrafi Konum", q: "Türkiye'nin 26°–45° doğu boylamları arasında yer almasının doğrudan sonucu hangisidir?", o: ["Doğu ile batı arasında 76 dakikalık yerel saat farkı olması", "Güneyden kuzeye sıcaklığın azalması", "Dört mevsimin belirgin yaşanması", "Kuzey yamaçların daha az güneş alması", "Gölge boylarının yıl içinde değişmesi"], a: 0, e: "Boylam farkı yerel saat farkını doğurur. Diğer seçenekler enlem ve eksen eğikliğiyle ilgilidir." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "Akdeniz ikliminin doğal bitki örtüsü aşağıdakilerden hangisidir?", o: ["Bozkır", "Maki", "Orman", "Çayır", "Tundra"], a: 1, e: "Kuraklığa dayanıklı, her mevsim yeşil kalabilen çalılardan oluşan maki, Akdeniz ikliminin bitki örtüsüdür." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "İç Anadolu'da ilkbaharda görülen kırkikindi yağmurları hangi yağış türüne örnektir?", o: ["Orografik (yamaç)", "Konveksiyonel (yükselim)", "Cephesel", "Kar", "Dolu"], a: 1, e: "Isınan havanın yükselip soğumasıyla oluşur; konveksiyonel yağıştır." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "Karadeniz kıyılarının her mevsim yağış almasının temel nedeni nedir?", o: ["Denizin tuzluluk oranının düşük olması", "Dağların kıyıya paralel uzanması ve nemli havanın yamaçlarda yükselmesi", "Enlemin yüksek olması", "Akarsuların çok olması", "Nüfusun yoğun olması"], a: 1, e: "Denizden gelen nemli hava, kıyıya paralel dağların yamaçlarında yükselip soğur ve orografik yağış bırakır." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "Aşağıdakilerden hangisi Türkiye'de iklim çeşitliliğinin nedenlerinden biri değildir?", o: ["Yer şekillerinin çeşitli olması", "Üç tarafının denizlerle çevrili olması", "Yükselti farklarının fazla olması", "Orta kuşakta yer alması", "Tek saat dilimi kullanılması"], a: 4, e: "Saat dilimi idari bir tercihtir; iklimi etkilemez." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Aşağıdaki göllerden hangisi heyelan set gölüdür?", o: ["Van Gölü", "Tuz Gölü", "Tortum Gölü", "Sapanca Gölü", "Nemrut Krater Gölü"], a: 2, e: "Tortum Gölü heyelanla vadinin önünün kapanmasıyla oluşmuştur. Van volkanik set, Tuz ve Sapanca tektonik, Nemrut kraterdir." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Ria tipi kıyıya örnek aşağıdakilerden hangisidir?", o: ["Ege kıyıları", "İstanbul Boğazı", "Doğu Karadeniz kıyıları", "Antalya kıyıları", "Çukurova kıyıları"], a: 1, e: "Akarsu vadisinin deniz sularıyla dolmasıyla oluşan ria kıyılara İstanbul Boğazı ve Haliç örnektir." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Aşağıdaki ovalardan hangisi delta ovası değildir?", o: ["Çukurova", "Bafra Ovası", "Çarşamba Ovası", "Silifke Ovası", "Konya Ovası"], a: 4, e: "Konya Ovası tektonik kökenlidir. Diğerleri akarsuların denize döküldüğü yerde biriktirdiği deltalardır." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Aşağıdakilerden hangisi karstik bir şekil değildir?", o: ["Obruk", "Dolin", "Traverten", "Polye", "Peribacası"], a: 4, e: "Peribacaları volkanik tüflerin sel suları ve rüzgârla aşınmasıyla oluşur. Karstik şekiller kalkerin erimesiyle oluşur." },
{ s: "cog", t: "Nüfus ve Yerleşme", q: "Cumhuriyet döneminin ilk nüfus sayımı hangi yıl yapılmıştır?", o: ["1923", "1927", "1935", "1940", "1950"], a: 1, e: "İlk nüfus sayımı 1927'de yapıldı; nüfus yaklaşık 13,6 milyondu." },
{ s: "cog", t: "Tarım ve Hayvancılık", q: "Türkiye'de fındık üretiminin en fazla olduğu il aşağıdakilerden hangisidir?", o: ["Rize", "Ordu", "Samsun", "Artvin", "Sinop"], a: 1, e: "Fındık üretiminde Ordu ve Giresun başı çeker. Rize çay üretimiyle öne çıkar." },
{ s: "cog", t: "Tarım ve Hayvancılık", q: "Büyükbaş hayvancılığın en yaygın olduğu bölge hangisidir?", o: ["Marmara", "Ege", "Doğu Anadolu", "Akdeniz", "Güneydoğu Anadolu"], a: 2, e: "Yaz yağışlarıyla gür otlakları olan Erzurum-Kars yöresinde büyükbaş hayvancılık yaygındır." },
{ s: "cog", t: "Madenler ve Enerji", q: "Aşağıdaki maden-yer eşleştirmelerinden hangisi yanlıştır?", o: ["Bor – Kırka (Eskişehir)", "Krom – Guleman (Elazığ)", "Boksit – Seydişehir (Konya)", "Taşkömürü – Soma (Manisa)", "Bakır – Murgul (Artvin)"], a: 3, e: "Soma'da linyit çıkarılır. Taşkömürünün çıkarıldığı yer Zonguldak'tır." },
{ s: "cog", t: "Madenler ve Enerji", q: "Türkiye'nin ilk jeotermal enerji santrali nerede kurulmuştur?", o: ["Aydın Germencik", "Denizli Sarayköy", "Afyon", "İzmir Balçova", "Kütahya Simav"], a: 1, e: "İlk jeotermal santral Denizli Sarayköy'de (Kızıldere) kurulmuştur." },
{ s: "cog", t: "Madenler ve Enerji", q: "Afşin-Elbistan termik santrallerinde yakıt olarak ne kullanılır?", o: ["Taşkömürü", "Linyit", "Doğal gaz", "Petrol", "Jeotermal buhar"], a: 1, e: "Kahramanmaraş Afşin-Elbistan, Türkiye'nin en büyük linyit havzasıdır." },
{ s: "cog", t: "Madenler ve Enerji", q: "Akkuyu Nükleer Güç Santrali hangi ildedir?", o: ["Sinop", "Mersin", "Antalya", "Adana", "Hatay"], a: 1, e: "Akkuyu NGS Mersin'in Gülnar ilçesindedir." },
{ s: "cog", t: "Bölgeler ve Projeler", q: "Aşağıdaki illerden hangisi GAP kapsamında değildir?", o: ["Batman", "Kilis", "Malatya", "Şırnak", "Adıyaman"], a: 2, e: "GAP illeri: Siirt, Batman, Adıyaman, Şanlıurfa, Şırnak, Mardin, Gaziantep, Kilis, Diyarbakır. Malatya GAP'ta değildir." },
{ s: "cog", t: "Bölgeler ve Projeler", q: "Türkiye'nin yüz ölçümü en büyük coğrafi bölgesi hangisidir?", o: ["İç Anadolu", "Doğu Anadolu", "Karadeniz", "Akdeniz", "Marmara"], a: 1, e: "En büyük bölge Doğu Anadolu, en küçük bölge Güneydoğu Anadolu'dur." },
{ s: "cog", t: "Sanayi, Ulaşım ve Turizm", q: "Türkiye'nin ilk demir-çelik fabrikası hangi ilde kurulmuştur?", o: ["Zonguldak", "Karabük", "Hatay", "Sivas", "Kocaeli"], a: 1, e: "Karabük Demir-Çelik Fabrikası 1937'de kurulmuştur." },

// ---------- VATANDAŞLIK ----------
{ s: "vat", t: "Yasama", q: "1982 Anayasası'na göre TBMM kaç milletvekilinden oluşur?", o: ["450", "500", "550", "600", "650"], a: 3, e: "2017 değişikliğiyle milletvekili sayısı 550'den 600'e çıkarıldı." },
{ s: "vat", t: "Yasama", q: "Bir anayasa değişikliği teklifinin halkoylamasına gerek kalmadan TBMM'de kabul edilebilmesi için en az kaç oy gerekir?", o: ["301", "360", "400", "450", "500"], a: 2, e: "Üye tamsayısının 2/3'ü (400) ile kabul edilen değişikliği CB isterse halkoyuna sunar. 360–399 oyda halkoylaması zorunludur." },
{ s: "vat", t: "Yasama", q: "TBMM'nin toplantı yeter sayısı kaçtır?", o: ["151", "200", "301", "360", "400"], a: 1, e: "Toplantı yeter sayısı üye tamsayısının 1/3'ü yani 200'dür." },
{ s: "vat", t: "Yürütme", q: "Cumhurbaşkanı seçilebilmek için gereken en az yaş kaçtır?", o: ["18", "25", "35", "40", "45"], a: 3, e: "40 yaşını doldurmuş, yükseköğrenim yapmış ve milletvekili seçilme yeterliliğine sahip olmak gerekir." },
{ s: "vat", t: "Yürütme", q: "Aşağıdakilerden hangisi TBMM'nin görev ve yetkilerinden biri değildir?", o: ["Kanun koymak", "Bütçe kanununu kabul etmek", "Savaş ilanına karar vermek", "Genel ve özel af ilanına karar vermek", "Cumhurbaşkanlığı kararnamesi çıkarmak"], a: 4, e: "Cumhurbaşkanlığı kararnamesi çıkarma yetkisi Cumhurbaşkanı'na aittir." },
{ s: "vat", t: "Yürütme", q: "Cumhurbaşkanı hakkında soruşturma açılmasına TBMM üye tamsayısının en az kaçının oyuyla karar verilebilir?", o: ["200", "301", "360", "400", "450"], a: 2, e: "Önerge salt çoğunluk (301), soruşturma açılması 3/5 (360), Yüce Divan'a sevk 2/3 (400) oyla olur." },
{ s: "vat", t: "1982 Anayasası: Genel Esaslar", q: "Aşağıdakilerden hangisi Anayasa'nın değiştirilmesi teklif dahi edilemeyecek hükümlerinden biri değildir?", o: ["Devletin şeklinin Cumhuriyet olması", "Başkentin Ankara olması", "Resmî dilin Türkçe olması", "Milletvekili sayısı", "Bayrak ve İstiklal Marşı"], a: 3, e: "İlk üç madde değiştirilemez. Milletvekili sayısı 2017'de değiştirilmiştir." },
{ s: "vat", t: "Yargı", q: "Anayasa Mahkemesi kaç üyeden oluşur?", o: ["11", "13", "15", "17", "21"], a: 2, e: "15 üye: 12'si Cumhurbaşkanı, 3'ü TBMM tarafından seçilir." },
{ s: "vat", t: "Yargı", q: "Hâkimler ve Savcılar Kurulu'nun başkanı kimdir?", o: ["Cumhurbaşkanı", "Yargıtay Başkanı", "Adalet Bakanı", "Anayasa Mahkemesi Başkanı", "TBMM Başkanı"], a: 2, e: "HSK'nın başkanı Adalet Bakanı, tabii üyesi Adalet Bakan Yardımcısıdır." },
{ s: "vat", t: "Yargı", q: "Sayıştay, kamu harcamalarını kimin adına denetler?", o: ["Cumhurbaşkanı", "TBMM", "Hazine ve Maliye Bakanlığı", "Danıştay", "Anayasa Mahkemesi"], a: 1, e: "Sayıştay, merkezî yönetim bütçesi kapsamındaki idarelerin gelir ve giderlerini TBMM adına denetler." },
{ s: "vat", t: "Anayasa Tarihi", q: "Osmanlı Devleti'nin ilk yazılı anayasası hangisidir?", o: ["Sened-i İttifak", "Tanzimat Fermanı", "Islahat Fermanı", "Kanun-i Esasi", "Teşkilat-ı Esasiye"], a: 3, e: "Kanun-i Esasi 23 Aralık 1876'da ilan edildi." },
{ s: "vat", t: "Anayasa Tarihi", q: "Anayasa Mahkemesi ve sosyal devlet ilkesi ilk kez hangi anayasada yer almıştır?", o: ["1876", "1921", "1924", "1961", "1982"], a: 3, e: "1961 Anayasası Anayasa Mahkemesi'ni kurdu, çift meclis sistemini getirdi ve sosyal devlet ilkesini benimsedi." },
{ s: "vat", t: "Anayasa Tarihi", q: "Aşağıdakilerden hangisi 1921 Teşkilat-ı Esasiye Kanunu'nun özelliklerinden biri değildir?", o: ["Güçler birliği ilkesini benimsemesi", "Millî egemenliği esas alması", "Kısa ve öz olması", "Temel hak ve özgürlüklere geniş yer vermesi", "Olağanüstü bir dönemde hazırlanması"], a: 3, e: "1921 Anayasası'nda temel hak ve özgürlüklere ilişkin hüküm yoktur." },
{ s: "vat", t: "Hukukun Temel Kavramları", q: "Türk Medeni Kanunu'na göre kişinin hak ehliyeti ne zaman başlar?", o: ["18 yaşını doldurunca", "Sağ doğmak koşuluyla ana rahmine düştüğü andan itibaren", "Nüfusa kaydedilince", "Ayırt etme gücüne sahip olunca", "Doğumdan bir yıl sonra"], a: 1, e: "Kişilik sağ doğumla başlar; ancak çocuk sağ doğmak koşuluyla ana rahmine düştüğü andan itibaren hak ehliyetine sahiptir." },
{ s: "vat", t: "Hukukun Temel Kavramları", q: "Aşağıdakilerden hangisi hukukun yazılı kaynaklarından biri değildir?", o: ["Anayasa", "Kanun", "Cumhurbaşkanlığı kararnamesi", "Yönetmelik", "Örf ve adet"], a: 4, e: "Örf ve adet yazısız kaynaktır." },
{ s: "vat", t: "Temel Hak ve Ödevler", q: "Aşağıdakilerden hangisi olağanüstü hâllerde bile dokunulamayan haklardandır?", o: ["Seyahat özgürlüğü", "Toplantı ve gösteri yürüyüşü hakkı", "Basın özgürlüğü", "Din ve vicdan özgürlüğü", "Mülkiyet hakkı"], a: 3, e: "Yaşam hakkı, maddi-manevi bütünlük, din ve vicdan özgürlüğü, suç ve cezaların geriye yürümezliği ve masumiyet karinesi dokunulmaz çekirdek alandadır." },
{ s: "vat", t: "Temel Hak ve Ödevler", q: "Aşağıdakilerden hangisi kişi hakları arasında yer almaz?", o: ["Konut dokunulmazlığı", "Haberleşme hürriyeti", "Yerleşme ve seyahat hürriyeti", "Çalışma hakkı", "Özel hayatın gizliliği"], a: 3, e: "Çalışma hakkı sosyal ve ekonomik haklardandır (pozitif statü)." },
{ s: "vat", t: "İdare Hukuku", q: "Aşağıdakilerden hangisi yer bakımından yerinden yönetim kuruluşu değildir?", o: ["Belediye", "İl özel idaresi", "Köy", "Valilik", "Büyükşehir belediyesi"], a: 3, e: "Valilik merkezî yönetimin taşra teşkilatıdır." },

// ---------- GÜNCEL ----------
{ s: "gun", t: "Uluslararası Kuruluşlar", q: "Aşağıdaki ülkelerden hangisi Türk Devletleri Teşkilatı'nın tam üyesi değil, gözlemcisidir?", o: ["Azerbaycan", "Kazakistan", "Kırgızistan", "Özbekistan", "Türkmenistan"], a: 4, e: "Türkmenistan, Macaristan ve KKTC gözlemci statüsündedir." },
{ s: "gun", t: "Uluslararası Kuruluşlar", q: "2024 yılında NATO'nun 32. üyesi olan ülke hangisidir?", o: ["Finlandiya", "İsveç", "Ukrayna", "Gürcistan", "İrlanda"], a: 1, e: "Finlandiya 2023'te, İsveç Mart 2024'te NATO'ya katıldı." },
{ s: "gun", t: "Uluslararası Kuruluşlar", q: "Türkiye NATO'ya hangi yıl üye olmuştur?", o: ["1949", "1950", "1952", "1955", "1963"], a: 2, e: "Türkiye, Yunanistan ile birlikte 1952'de NATO'ya katıldı." },
{ s: "gun", t: "Türkiye'de Büyük Projeler", q: "Türkiye'nin ilk yerli ve millî haberleşme uydusu hangisidir?", o: ["Türksat 5A", "Türksat 5B", "Türksat 6A", "Göktürk-1", "İMECE"], a: 2, e: "Türksat 6A, Temmuz 2024'te fırlatılan ilk yerli ve millî haberleşme uydusudur. İMECE bir gözlem uydusudur." },
{ s: "gun", t: "Türkiye'de Büyük Projeler", q: "18 Mart 2022'de açılan, dünyanın en uzun orta açıklıklı asma köprüsü hangisidir?", o: ["Osmangazi Köprüsü", "Yavuz Sultan Selim Köprüsü", "1915 Çanakkale Köprüsü", "15 Temmuz Şehitler Köprüsü", "Fatih Sultan Mehmet Köprüsü"], a: 2, e: "1915 Çanakkale Köprüsü'nün orta açıklığı 2023 metredir." },
{ s: "gun", t: "Türkiye'de Büyük Projeler", q: "Sakarya Gaz Sahası hangi denizde yer almaktadır?", o: ["Marmara Denizi", "Ege Denizi", "Akdeniz", "Karadeniz", "Kızıldeniz"], a: 3, e: "2020'de Karadeniz'de keşfedildi; ilk gaz 2023'te Filyos'a ulaştı." },
{ s: "gun", t: "Kültür ve Miras", q: "Aşağıdakilerden hangisi 2023 yılında UNESCO Dünya Mirası Listesi'ne girmiştir?", o: ["Göbeklitepe", "Efes", "Gordion", "Afrodisias", "Arslantepe"], a: 2, e: "Gordion 2023'te listeye girdi. Göbeklitepe 2018, Efes 2015, Afrodisias 2017, Arslantepe 2021." },

// ---------- EĞİTİM BİLİMLERİ ----------
{ s: "eb", t: "Gelişim Psikolojisi", q: "Bir bardaktaki suyun şekli farklı bir bardağa döküldüğünde miktarının değişmediğini anlayan çocuk, Piaget'e göre hangi dönemdedir?", o: ["Duyusal-motor", "İşlem öncesi", "Somut işlemler", "Soyut işlemler", "Sezgisel dönem"], a: 2, e: "Korunum ilkesi somut işlemler döneminde (7–11 yaş) kazanılır." },
{ s: "eb", t: "Gelişim Psikolojisi", q: "Nesne sürekliliği Piaget'e göre hangi dönemde kazanılır?", o: ["Duyusal-motor", "İşlem öncesi", "Somut işlemler", "Soyut işlemler", "Ergenlik"], a: 0, e: "Gözden kaybolan nesnenin var olmaya devam ettiğini anlamak duyusal-motor dönemde (0–2) gelişir." },
{ s: "eb", t: "Gelişim Psikolojisi", q: "Erikson'a göre ergenlik döneminin temel krizi hangisidir?", o: ["Güvene karşı güvensizlik", "Girişimciliğe karşı suçluluk", "Başarıya karşı aşağılık", "Kimlik kazanmaya karşı rol karmaşası", "Yakınlığa karşı yalnızlık"], a: 3, e: "12–18 yaş: kimlik kazanmaya karşı rol karmaşası." },
{ s: "eb", t: "Gelişim Psikolojisi", q: "Yalnızca ceza almamak için kurallara uyan bir çocuk, Kohlberg'e göre hangi düzeydedir?", o: ["Gelenek öncesi", "Geleneksel", "Gelenek sonrası", "Evrensel ahlak", "Sosyal sözleşme"], a: 0, e: "Ceza-itaat yönelimi gelenek öncesi düzeyin ilk basamağıdır." },
{ s: "eb", t: "Gelişim Psikolojisi", q: "Çocuğun tek başına yapamadığı ancak bir yetişkinin desteğiyle yapabildiği görevler alanına ne ad verilir?", o: ["Kritik dönem", "Yakınsal gelişim alanı", "Özümseme", "Dengeleme", "Hazırbulunuşluk"], a: 1, e: "Vygotsky'nin yakınsal gelişim alanı kavramıdır; bu alandaki desteğe iskele kurma denir." },
{ s: "eb", t: "Öğrenme Psikolojisi", q: "Hoşa gitmeyen bir uyaranın ortamdan kaldırılarak bir davranışın sıklığının artırılmasına ne ad verilir?", o: ["Olumlu pekiştirme", "Olumsuz pekiştirme", "1. tür ceza", "2. tür ceza", "Sönme"], a: 1, e: "Pekiştirme davranışı artırır. Hoşa gitmeyen uyaran kaldırıldığı için bu olumsuz pekiştirmedir." },
{ s: "eb", t: "Öğrenme Psikolojisi", q: "Sönmeye karşı en dirençli davranışları oluşturan pekiştirme tarifesi hangisidir?", o: ["Sabit oranlı", "Değişken oranlı", "Sabit aralıklı", "Değişken aralıklı", "Sürekli pekiştirme"], a: 1, e: "Değişken oranlı tarifede ne zaman pekiştireç geleceği bilinmez; kumar makinesi örneğidir." },
{ s: "eb", t: "Öğrenme Psikolojisi", q: "Model alma, dolaylı pekiştirme ve öz yeterlik kavramları hangi kuramcıya aittir?", o: ["Pavlov", "Skinner", "Bandura", "Piaget", "Thorndike"], a: 2, e: "Albert Bandura'nın sosyal bilişsel öğrenme kuramıdır." },
{ s: "eb", t: "Öğretim Yöntemleri", q: "Ön örgütleyicilerin kullanıldığı sunuş yoluyla öğretim stratejisi hangi kuramcıya aittir?", o: ["Bruner", "Ausubel", "Dewey", "Gagné", "Bloom"], a: 1, e: "Ausubel'in anlamlı öğrenme ve sunuş yoluyla öğretim yaklaşımıdır." },
{ s: "eb", t: "Öğretim Yöntemleri", q: "Buluş yoluyla öğretim ve sarmal program yaklaşımı hangi kuramcıyla ilişkilidir?", o: ["Ausubel", "Bruner", "Tyler", "Skinner", "Gardner"], a: 1, e: "Jerome Bruner, tümevarıma dayalı buluş yoluyla öğretimi savunmuştur." },
{ s: "eb", t: "Ölçme ve Değerlendirme", q: "Celsius cinsinden ölçülen sıcaklık hangi ölçek türüne örnektir?", o: ["Sınıflama", "Sıralama", "Eşit aralıklı", "Oranlı", "Mutlak"], a: 2, e: "0 °C sıcaklığın yokluğu anlamına gelmez; mutlak sıfır olmadığı için eşit aralıklı ölçektir." },
{ s: "eb", t: "Ölçme ve Değerlendirme", q: "Aynı testin aynı gruba iki farklı zamanda uygulanıp puanlar arasındaki tutarlılığa bakılması neyin belirlenmesine yöneliktir?", o: ["Kapsam geçerliği", "Yapı geçerliği", "Test-tekrar test güvenirliği", "Madde güçlüğü", "Ayırt edicilik"], a: 2, e: "Zamana göre tutarlılık test-tekrar test güvenirliğidir." },
{ s: "eb", t: "Program Geliştirme", q: "Revize edilmiş Bloom taksonomisinin bilişsel alandaki en üst basamağı hangisidir?", o: ["Değerlendirme", "Çözümleme", "Yaratma", "Uygulama", "Sentez"], a: 2, e: "Revize taksonomi: hatırlama, anlama, uygulama, çözümleme, değerlendirme, yaratma." },
{ s: "eb", t: "Rehberlik", q: "Okul rehberlik hizmetlerinin çekirdeğini oluşturan hizmet hangisidir?", o: ["Bilgi verme", "Bireyi tanıma", "Psikolojik danışma", "Yöneltme ve yerleştirme", "İzleme"], a: 2, e: "Psikolojik danışma, rehberlik hizmetlerinin merkezinde yer alır." },

// ---------- ÖNLİSANS EK: TARİH ----------
{ s: "tar", t: "İslamiyet Öncesi Türk Tarihi", q: "Asya Hun Devleti'nde hükümdarlar hangi unvanı kullanmıştır?", o: ["Kağan", "Tanhu", "Yabgu", "Han", "Sultan"], a: 1, e: "Asya Hun hükümdarları “Tanhu” unvanını kullanmıştır. Kağan unvanı Göktürklerle yaygınlaşmıştır." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "“Sultan” unvanını kullanan ilk Türk hükümdarı kimdir?", o: ["Alparslan", "Satuk Buğra Han", "Gazneli Mahmut", "Tuğrul Bey", "Melikşah"], a: 2, e: "Gazneli Mahmut, “sultan” unvanını kullanan ilk Türk hükümdarıdır." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "751 Talas Savaşı'nın kültürel alandaki en önemli sonucu hangisidir?", o: ["Kâğıt yapımının İslam dünyasına geçmesi", "Haçlı seferlerinin başlaması", "Anadolu'nun fethedilmesi", "Bizans'ın yıkılması", "Moğol istilasının başlaması"], a: 0, e: "Esir alınan Çinli ustalar sayesinde kâğıt yapımı Semerkant üzerinden İslam dünyasına geçti." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "Türkiye Selçuklularının başkentini İznik'ten Konya'ya taşımasına neden olan gelişme hangisidir?", o: ["Malazgirt Savaşı", "I. Haçlı Seferi", "Kösedağ Savaşı", "Moğol istilası", "Miryokefalon Savaşı"], a: 1, e: "I. Haçlı Seferi (1096–1099) sırasında İznik kaybedilince başkent Konya'ya taşındı." },
{ s: "tar", t: "İlk Türk-İslam Devletleri", q: "Anadolu'nun Moğol egemenliğine girmesine yol açan savaş hangisidir?", o: ["Yassıçemen", "Kösedağ", "Miryokefalon", "Malazgirt", "Ankara"], a: 1, e: "1243 Kösedağ Savaşı'nda Türkiye Selçukluları Moğollara yenildi." },
{ s: "tar", t: "Osmanlı Kültür ve Medeniyeti", q: "Osmanlı Devleti'nin ilk tersanesi nerede kurulmuştur?", o: ["Gelibolu", "Karamürsel", "Haliç", "Sinop", "İzmit"], a: 1, e: "İlk tersane Orhan Bey döneminde Karamürsel'de kuruldu." },
{ s: "tar", t: "Osmanlı Kültür ve Medeniyeti", q: "Teşkilat kanunnamesi olarak da bilinen “Kanunname-i Âl-i Osman”ı hazırlatan padişah kimdir?", o: ["Orhan Bey", "I. Murat", "Fatih Sultan Mehmet", "Kanuni Sultan Süleyman", "Yavuz Sultan Selim"], a: 2, e: "Fatih Sultan Mehmet devlet teşkilatını düzenleyen kanunnameyi hazırlattı." },
{ s: "tar", t: "Osmanlı Kültür ve Medeniyeti", q: "1826'da Yeniçeri Ocağı'nın kaldırılmasına verilen ad hangisidir?", o: ["Vaka-i Hayriye", "Nizam-ı Cedid", "Sened-i İttifak", "Kabakçı Mustafa İsyanı", "Patrona Halil İsyanı"], a: 0, e: "II. Mahmut döneminde Yeniçeri Ocağı'nın kaldırılmasına “Vaka-i Hayriye” (hayırlı olay) denir." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Halifeliğin Osmanlı Devleti'ne geçmesini sağlayan savaş hangisidir?", o: ["Çaldıran", "Mercidabık", "Ridaniye", "Mohaç", "Preveze"], a: 2, e: "1517 Ridaniye Savaşı'yla Memlükler yıkıldı ve halifelik Osmanlı'ya geçti." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Tanzimat Fermanı hangi padişah döneminde ilan edilmiştir?", o: ["II. Mahmut", "Abdülmecit", "Abdülaziz", "II. Abdülhamit", "III. Selim"], a: 1, e: "Tanzimat Fermanı 1839'da Abdülmecit döneminde ilan edildi." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Islahat Fermanı'nın (1856) ilan edilmesinde etkili olan savaş hangisidir?", o: ["93 Harbi", "Kırım Savaşı", "Balkan Savaşları", "Trablusgarp Savaşı", "Mora İsyanı"], a: 1, e: "Kırım Savaşı sonunda toplanan Paris Konferansı öncesinde, Avrupa'nın iç işlerine karışmasını önlemek için ilan edildi." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Padişahın yetkilerinin ilk kez sınırlandığı belge hangisidir?", o: ["Tanzimat Fermanı", "Sened-i İttifak", "Islahat Fermanı", "Kanun-i Esasi", "Misak-ı Milli"], a: 1, e: "1808 Sened-i İttifak, II. Mahmut ile ayanlar arasında imzalandı." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Osmanlı Devleti ilk kez hangi savaş sırasında dış borç almıştır?", o: ["Kırım Savaşı", "Lale Devri", "Tanzimat'ın ilanı", "93 Harbi", "I. Dünya Savaşı"], a: 0, e: "İlk dış borç 1854'te Kırım Savaşı sırasında İngiltere'den alındı." },
{ s: "tar", t: "Osmanlı Siyasi Tarihi", q: "Osmanlı Devleti'nin borçlarını ödeyemez hâle gelmesi üzerine 1881'de kurulan kuruluş hangisidir?", o: ["Düyun-ı Umumiye", "Osmanlı Bankası", "Ziraat Bankası", "Maarif Nezareti", "Meclis-i Mebusan"], a: 0, e: "Düyun-ı Umumiye, alacaklı devletler adına bazı vergileri doğrudan topladı." },
{ s: "tar", t: "Kurtuluş Savaşı: Hazırlık", q: "Mustafa Kemal'in işgalleri protesto etmek için mitingler düzenlenmesini istediği genelge hangisidir?", o: ["Havza Genelgesi", "Amasya Genelgesi", "Erzurum Kongresi", "Sivas Kongresi", "Amasya Görüşmeleri"], a: 0, e: "28 Mayıs 1919 Havza Genelgesi ile yurt genelinde protesto mitingleri yapıldı." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "Düzenli ordunun kazandığı ilk zafer hangisidir?", o: ["Sakarya", "I. İnönü", "II. İnönü", "Büyük Taarruz", "Kütahya-Eskişehir"], a: 1, e: "Ocak 1921 I. İnönü Savaşı düzenli ordunun ilk zaferidir; Londra Konferansı'nın toplanmasını sağladı." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "İstiklal Marşı TBMM'de hangi tarihte kabul edilmiştir?", o: ["23 Nisan 1920", "20 Ocak 1921", "12 Mart 1921", "1 Kasım 1922", "29 Ekim 1923"], a: 2, e: "Mehmet Akif Ersoy'un yazdığı İstiklal Marşı 12 Mart 1921'de kabul edildi." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "Bugünkü doğu sınırımızın kesinlik kazandığı antlaşma hangisidir?", o: ["Gümrü", "Moskova", "Kars", "Ankara", "Lozan"], a: 2, e: "13 Ekim 1921 Kars Antlaşması Ermenistan, Gürcistan ve Azerbaycan ile imzalandı." },
{ s: "tar", t: "Kurtuluş Savaşı: Cepheler ve Antlaşmalar", q: "Lozan Barış Konferansı'nda çözüme kavuşturulamayan konu hangisidir?", o: ["Kapitülasyonlar", "Boğazlar", "Irak sınırı (Musul)", "Nüfus mübadelesi", "Savaş tazminatı"], a: 2, e: "Musul sorunu İngiltere ile ikili görüşmelere bırakıldı; 1926 Ankara Antlaşması ile Irak'a bırakıldı." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Cumhuriyetin ilanından sonra kurulan ilk hükümetin başbakanı kimdir?", o: ["Ali Fethi Okyar", "İsmet İnönü", "Kazım Karabekir", "Rauf Orbay", "Celal Bayar"], a: 1, e: "29 Ekim 1923'te Mustafa Kemal Cumhurbaşkanı, İsmet Paşa başbakan oldu." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Ankara hangi tarihte başkent ilan edilmiştir?", o: ["23 Nisan 1920", "13 Ekim 1923", "29 Ekim 1923", "3 Mart 1924", "20 Nisan 1924"], a: 1, e: "Ankara, Cumhuriyetin ilanından iki hafta önce, 13 Ekim 1923'te başkent oldu." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Terakkiperver Cumhuriyet Fırkası'nın kapatılmasına yol açan olay hangisidir?", o: ["Menemen Olayı", "Şeyh Said İsyanı", "İzmir Suikastı", "Çerkez Ethem İsyanı", "31 Mart Olayı"], a: 1, e: "1925 Şeyh Said İsyanı sonrasında Takrir-i Sükun Kanunu çıkarıldı ve parti kapatıldı." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "1930'da kurulan Serbest Cumhuriyet Fırkası'nın kurucusu kimdir?", o: ["Kazım Karabekir", "Ali Fethi Okyar", "Rauf Orbay", "Adnan Menderes", "Celal Bayar"], a: 1, e: "Mustafa Kemal'in isteğiyle Ali Fethi Okyar kurdu; kısa süre sonra kendini feshetti." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Türk Medeni Kanunu hangi ülkenin medeni kanunu örnek alınarak hazırlanmıştır?", o: ["İsviçre", "İtalya", "Almanya", "Fransa", "İngiltere"], a: 0, e: "17 Şubat 1926'da kabul edilen Medeni Kanun İsviçre'den alındı. Ceza Kanunu İtalya'dan alındı." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Devletçilik ilkesinin ekonomide uygulanmasına geçilmesinde etkili olan gelişme hangisidir?", o: ["1929 Dünya Ekonomik Bunalımı", "İzmir İktisat Kongresi", "Lozan Antlaşması", "II. Dünya Savaşı", "Kabotaj Kanunu"], a: 0, e: "Özel sektörün yetersizliği ve 1929 bunalımı sonrasında devlet eliyle sanayileşmeye geçildi (I. Beş Yıllık Sanayi Planı, 1934)." },
{ s: "tar", t: "Atatürk İlke ve İnkılapları", q: "Harf İnkılabından sonra halka yeni harflerle okuma-yazma öğretmek için açılan kurum hangisidir?", o: ["Köy Enstitüleri", "Millet Mektepleri", "Halkevleri", "Darülfünun", "Mekteb-i Mülkiye"], a: 1, e: "Millet Mektepleri 1928'de Harf İnkılabının ardından açıldı." },
{ s: "tar", t: "Atatürk Dönemi Dış Politika", q: "Musul sorunu hangi devletle yapılan antlaşmayla çözülmüştür?", o: ["Fransa", "İngiltere", "İtalya", "Yunanistan", "Sovyet Rusya"], a: 1, e: "1926 Ankara Antlaşması İngiltere ve Irak ile imzalandı; Musul Irak'a bırakıldı." },
{ s: "tar", t: "Atatürk Dönemi Dış Politika", q: "Lozan'da imzalanan sözleşmeyle nüfus mübadelesi hangi ülkeyle yapılmıştır?", o: ["Bulgaristan", "Yunanistan", "Romanya", "Yugoslavya", "Arnavutluk"], a: 1, e: "Türkiye'deki Rumlarla Yunanistan'daki Türkler karşılıklı yer değiştirdi (İstanbul Rumları ve Batı Trakya Türkleri hariç)." },
{ s: "tar", t: "Çağdaş Türk ve Dünya Tarihi", q: "Kıbrıs Barış Harekâtı hangi yıl gerçekleştirilmiştir?", o: ["1964", "1967", "1974", "1983", "1990"], a: 2, e: "Kıbrıs Barış Harekâtı 20 Temmuz 1974'te başladı. KKTC 1983'te kuruldu." },

// ---------- ÖNLİSANS EK: COĞRAFYA ----------
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Türkiye'nin yüz ölçümü en büyük gölü hangisidir?", o: ["Tuz Gölü", "Beyşehir Gölü", "Van Gölü", "Eğirdir Gölü", "İznik Gölü"], a: 2, e: "Van Gölü en büyük gölümüzdür; ikinci sırada Tuz Gölü gelir." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Fırat ve Dicle nehirleri nereye dökülür?", o: ["Akdeniz", "Basra Körfezi", "Hazar Denizi", "Karadeniz", "Kızıldeniz"], a: 1, e: "Fırat ve Dicle Irak'ta birleşerek Şattülarap adıyla Basra Körfezi'ne dökülür." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Tuz Gölü oluşumu bakımından hangi göl türüne girer?", o: ["Volkanik", "Tektonik", "Karstik", "Buzul", "Heyelan set"], a: 1, e: "Tuz Gölü yer kabuğu hareketleriyle oluşmuş çukurda yer alan tektonik bir göldür." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Peribacalarının oluşumunda etkili olan kayaç hangisidir?", o: ["Kalker", "Volkanik tüf", "Granit", "Mermer", "Kum taşı"], a: 1, e: "Nevşehir'deki peribacaları, volkanik tüflerin sel suları ve rüzgârla aşınmasıyla oluşmuştur." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Kızılırmak'ın denize döküldüğü yerde oluşturduğu delta ovası hangisidir?", o: ["Çarşamba", "Bafra", "Silifke", "Çukurova", "Menemen"], a: 1, e: "Bafra Ovası Kızılırmak'ın, Çarşamba Ovası Yeşilırmak'ın deltasıdır." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Türkiye ile Yunanistan arasındaki sınırın bir bölümünü oluşturan akarsu hangisidir?", o: ["Meriç", "Aras", "Asi", "Çoruh", "Sakarya"], a: 0, e: "Meriç Nehri, Türkiye-Yunanistan sınırının büyük bölümünü oluşturur." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Marmara Bölgesi'nden Doğu Anadolu'ya kadar uzanan, ülkemizin en önemli fay hattı hangisidir?", o: ["Kuzey Anadolu Fay Hattı", "Doğu Anadolu Fay Hattı", "Batı Anadolu Fay Sistemi", "Ölü Deniz Fayı", "Ege Graben Sistemi"], a: 0, e: "Kuzey Anadolu Fay Hattı Saros Körfezi'nden Doğu Anadolu'ya kadar uzanır; 1999 Marmara depremi bu hatta oldu." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "Türkiye'de yıllık yağış miktarının en fazla olduğu il hangisidir?", o: ["Rize", "Antalya", "Muğla", "İstanbul", "Zonguldak"], a: 0, e: "Doğu Karadeniz kıyısında yer alan Rize yılda 2000 mm'nin üzerinde yağış alır." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "Türkiye'de yıllık yağışın en az olduğu yer hangisidir?", o: ["Tuz Gölü çevresi", "Doğu Karadeniz kıyıları", "Menteşe yöresi", "Teke yöresi", "Yıldız Dağları"], a: 0, e: "Çevresi dağlarla çevrili, denizden uzak Tuz Gölü çevresi yılda yaklaşık 300 mm yağış alır." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "Yıllık sıcaklık farkının en fazla olduğu bölge hangisidir?", o: ["Doğu Karadeniz kıyıları", "Doğu Anadolu", "Ege kıyıları", "Marmara", "Akdeniz kıyıları"], a: 1, e: "Karasallığın en güçlü olduğu Doğu Anadolu'da kışlar çok soğuk, yazlar sıcaktır. En az fark Karadeniz kıyılarındadır." },
{ s: "cog", t: "İklim ve Bitki Örtüsü", q: "Türkiye'de en geniş alanda etkili olan iklim tipi hangisidir?", o: ["Akdeniz iklimi", "Karadeniz iklimi", "Karasal iklim", "Marmara (geçiş) iklimi", "Çöl iklimi"], a: 2, e: "İç Anadolu, Doğu Anadolu ve Güneydoğu Anadolu'nun büyük kısmında karasal iklim görülür." },
{ s: "cog", t: "Yer Şekilleri ve Sular", q: "Heyelanın en sık görüldüğü bölge hangisidir?", o: ["İç Anadolu", "Karadeniz", "Güneydoğu Anadolu", "Ege", "Akdeniz"], a: 1, e: "Eğimin fazla olması, bol yağış ve killi topraklar Karadeniz'de heyelanı artırır." },
{ s: "cog", t: "Nüfus ve Yerleşme", q: "Nüfus yoğunluğunun en az olduğu coğrafi bölge hangisidir?", o: ["Marmara", "Doğu Anadolu", "Karadeniz", "Ege", "Akdeniz"], a: 1, e: "Engebeli arazi ve sert iklim nedeniyle Doğu Anadolu en seyrek nüfuslu bölgedir. En yoğun bölge Marmara'dır." },
{ s: "cog", t: "Tarım ve Hayvancılık", q: "Zeytin üretiminde ilk sırada yer alan bölge hangisidir?", o: ["Akdeniz", "Ege", "Marmara", "Güneydoğu Anadolu", "Karadeniz"], a: 1, e: "Zeytin üretiminin en fazla olduğu bölge Ege'dir." },
{ s: "cog", t: "Tarım ve Hayvancılık", q: "Ankara keçisi (tiftik keçisi) yetiştiriciliği en çok hangi bölgede yapılır?", o: ["İç Anadolu", "Karadeniz", "Ege", "Marmara", "Akdeniz"], a: 0, e: "Tiftik keçisi kurak ve karasal koşullara uygundur; İç Anadolu'da, özellikle Ankara çevresinde yetiştirilir." },
{ s: "cog", t: "Madenler ve Enerji", q: "Atatürk Barajı hangi akarsu üzerinde kurulmuştur?", o: ["Dicle", "Fırat", "Kızılırmak", "Seyhan", "Ceyhan"], a: 1, e: "Atatürk, Keban ve Karakaya barajları Fırat üzerindedir. Ilısu Barajı Dicle üzerindedir." },
{ s: "cog", t: "Madenler ve Enerji", q: "Rüzgâr santrallerinin en çok kurulduğu bölgeler hangileridir?", o: ["Ege ve Marmara", "İç Anadolu ve Doğu Anadolu", "Karadeniz ve Doğu Anadolu", "Güneydoğu Anadolu", "Akdeniz ve İç Anadolu"], a: 0, e: "Sürekli ve güçlü rüzgâr alan İzmir, Balıkesir ve Çanakkale öne çıkar." },
{ s: "cog", t: "Sanayi, Ulaşım ve Turizm", q: "Karabük Demir-Çelik Fabrikası'nın kuruluş yerinin seçiminde en etkili faktör hangisidir?", o: ["Demir madenine yakınlık", "Taşkömürü havzasına yakınlık", "Liman olanağı", "Pazara yakınlık", "İş gücü fazlalığı"], a: 1, e: "Demir cevheri Divriği'den getirilir; fabrika enerji kaynağı olan Zonguldak taşkömürüne yakın kurulmuştur." },
{ s: "cog", t: "Sanayi, Ulaşım ve Turizm", q: "Aşağıdaki illerin hangisinde petrol rafinerisi yoktur?", o: ["Kocaeli", "İzmir", "Kırıkkale", "Batman", "Konya"], a: 4, e: "Rafineriler İzmit (Kocaeli), Aliağa (İzmir), Kırıkkale ve Batman'dadır." },
{ s: "cog", t: "Sanayi, Ulaşım ve Turizm", q: "İstanbul Boğazı'nın altından geçen demiryolu tüp tüneli hangisidir?", o: ["Avrasya Tüneli", "Marmaray", "Yavuz Sultan Selim Köprüsü", "Osmangazi Köprüsü", "1915 Çanakkale Köprüsü"], a: 1, e: "Marmaray 2013'te açıldı. Avrasya Tüneli ise karayolu tünelidir (2016)." },

// ---------- ÖNLİSANS EK: VATANDAŞLIK ----------
{ s: "vat", t: "Yasama", q: "Cumhurbaşkanı, TBMM'nin kabul ettiği kanunları kaç gün içinde yayımlar?", o: ["7", "10", "15", "30", "45"], a: 2, e: "CB kanunları 15 gün içinde yayımlar ya da bir kez daha görüşülmek üzere TBMM'ye geri gönderir." },
{ s: "vat", t: "Yasama", q: "2017 Anayasa değişikliğinden sonra kanun teklif etme yetkisi kime aittir?", o: ["Cumhurbaşkanı", "Milletvekilleri", "Bakanlar", "Anayasa Mahkemesi", "Cumhurbaşkanı yardımcıları"], a: 1, e: "Kanun teklif etmeye yalnızca milletvekilleri yetkilidir. Bakanlar Kurulu kaldırıldığı için “kanun tasarısı” da kalmamıştır." },
{ s: "vat", t: "Yürütme", q: "Merkezî yönetim bütçe kanunu teklifini TBMM'ye kim sunar?", o: ["Hazine ve Maliye Bakanı", "Cumhurbaşkanı", "Plan ve Bütçe Komisyonu", "Sayıştay", "Merkez Bankası"], a: 1, e: "Cumhurbaşkanı bütçe teklifini mali yılbaşından en az 75 gün önce TBMM'ye sunar." },
{ s: "vat", t: "Yürütme", q: "Olağanüstü hâl en fazla ne kadar süreyle ilan edilebilir?", o: ["1 ay", "3 ay", "6 ay", "1 yıl", "2 yıl"], a: 2, e: "CB olağanüstü hâli 6 ayı geçmemek üzere ilan eder; TBMM uzatabilir (her seferinde en çok 4 ay)." },
{ s: "vat", t: "Yürütme", q: "Milletvekilleri arasından Cumhurbaşkanı yardımcısı ya da bakan olarak atananların TBMM üyelikleri ne olur?", o: ["Üyelikleri sona erer", "Üyelikleri askıya alınır", "Üyelikleri devam eder", "TBMM onayıyla devam eder", "Bir yıl sonra sona erer"], a: 0, e: "Anayasa m.106: TBMM üyeleri arasından atananların üyelikleri sona erer." },
{ s: "vat", t: "Yargı", q: "İdari yargının en üst mahkemesi hangisidir?", o: ["Yargıtay", "Danıştay", "Sayıştay", "Uyuşmazlık Mahkemesi", "Anayasa Mahkemesi"], a: 1, e: "Danıştay idari yargının, Yargıtay adli yargının son inceleme merciidir." },
{ s: "vat", t: "Yargı", q: "Adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını çözen mahkeme hangisidir?", o: ["Anayasa Mahkemesi", "Yargıtay", "Danıştay", "Uyuşmazlık Mahkemesi", "Bölge adliye mahkemesi"], a: 3, e: "Uyuşmazlık Mahkemesi bu tür uyuşmazlıkları kesin olarak çözer." },
{ s: "vat", t: "Yargı", q: "Siyasi partilerin kapatılmasına hangi mahkeme karar verir?", o: ["Yargıtay", "Anayasa Mahkemesi", "Danıştay", "Yüksek Seçim Kurulu", "TBMM"], a: 1, e: "Kapatma davasını Yargıtay Cumhuriyet Başsavcısı açar, kararı Anayasa Mahkemesi verir." },
{ s: "vat", t: "Yargı", q: "Anayasada güvence altına alınan bir temel hakkının kamu gücü tarafından ihlal edildiğini iddia eden kişi hangi yola başvurabilir?", o: ["Anayasa Mahkemesi'ne bireysel başvuru", "Yargıtay'a temyiz", "Sayıştay'a şikâyet", "YSK'ya itiraz", "Uyuşmazlık Mahkemesi'ne başvuru"], a: 0, e: "Bireysel başvuru 2010 değişikliğiyle getirildi, 2012'den beri uygulanıyor. Önce olağan kanun yolları tüketilmelidir." },
{ s: "vat", t: "Yargı", q: "Anayasa Mahkemesi üyelerinin görev süresi kaç yıldır?", o: ["4", "7", "9", "12", "15"], a: 3, e: "Üyeler 12 yıl için seçilir ve bir kez daha seçilemez." },
{ s: "vat", t: "Temel Hak ve Ödevler", q: "Seçimlerin genel yönetim ve denetimini yapan kurum hangisidir?", o: ["Yüksek Seçim Kurulu", "Anayasa Mahkemesi", "İçişleri Bakanlığı", "TBMM Başkanlığı", "Danıştay"], a: 0, e: "YSK seçimlerin başından sonuna kadar genel yönetim ve denetimini yapar; kararlarına karşı başka mercie başvurulamaz." },
{ s: "vat", t: "Temel Hak ve Ödevler", q: "Aşağıdakilerden hangisi 1982 Anayasası'nda siyasi haklar ve ödevler arasında düzenlenmiştir?", o: ["Dilekçe hakkı", "Eğitim hakkı", "Konut dokunulmazlığı", "Çalışma hakkı", "Sağlık hakkı"], a: 0, e: "Dilekçe, bilgi edinme ve kamu denetçisine başvurma hakkı siyasi haklar bölümündedir." },
{ s: "vat", t: "Temel Hak ve Ödevler", q: "Anayasa'ya göre herkes, kamu giderlerini karşılamak üzere mali gücüne göre neyle yükümlüdür?", o: ["Vergi ödemekle", "Askerlik yapmakla", "Oy kullanmakla", "Çalışmakla", "Eğitim almakla"], a: 0, e: "Anayasa m.73 vergi ödevini düzenler." },
{ s: "vat", t: "Hukukun Temel Kavramları", q: "Aşağıdakilerden hangisi özel hukuk dallarından biridir?", o: ["Anayasa hukuku", "İdare hukuku", "Ceza hukuku", "Medeni hukuk", "Vergi hukuku"], a: 3, e: "Özel hukuk: medeni, borçlar, ticaret hukuku. Kamu hukuku: anayasa, idare, ceza, vergi hukuku." },
{ s: "vat", t: "Hukukun Temel Kavramları", q: "Bir kimsenin sürekli kalma niyetiyle oturduğu yere ne ad verilir?", o: ["Yerleşim yeri", "İkametgâh izni", "Nüfus kaydı", "Tabiiyet", "Hısımlık"], a: 0, e: "Türk Medeni Kanunu'na göre yerleşim yeri, sürekli kalma niyetiyle oturulan yerdir. Kimse aynı anda birden çok yerleşim yerine sahip olamaz." },
{ s: "vat", t: "İdare Hukuku", q: "Valiler hangi makam tarafından atanır?", o: ["İçişleri Bakanı", "Cumhurbaşkanı", "TBMM", "Halk tarafından seçilir", "İl genel meclisi"], a: 1, e: "Valiler Cumhurbaşkanı kararıyla atanır; ilde devletin ve Cumhurbaşkanının temsilcisidir." },
{ s: "vat", t: "İdare Hukuku", q: "Aşağıdakilerden hangisi belediyenin organlarından biridir?", o: ["Belediye encümeni", "İl genel meclisi", "Köy derneği", "İhtiyar heyeti", "Vilayet idare kurulu"], a: 0, e: "Belediyenin organları: belediye meclisi, belediye encümeni, belediye başkanı. İl genel meclisi il özel idaresinin; köy derneği ve ihtiyar heyeti köyün organıdır." },
{ s: "vat", t: "İdare Hukuku", q: "Kamu Denetçiliği Kurumu (Ombudsman) hangi makama bağlıdır?", o: ["Cumhurbaşkanlığı", "TBMM Başkanlığı", "Adalet Bakanlığı", "İçişleri Bakanlığı", "Danıştay"], a: 1, e: "Kamu Denetçiliği Kurumu, idarenin işleyişiyle ilgili şikâyetleri incelemek üzere TBMM Başkanlığına bağlı olarak kurulmuştur." }
];

window.K = {
tr: [
["Büyük ünlü uyumu nedir?", "İlk hecede kalın ünlü (a, ı, o, u) varsa sonrakiler kalın; ince ünlü (e, i, ö, ü) varsa ince olur. Uymayan ekler: -ken, -leyin, -daş, -yor, -ki, -gil."],
["Sert ünsüzlerin kodu?", "FıSTıKÇı ŞaHaP → f, s, t, k, ç, ş, h, p"],
["Ünsüz benzeşmesi (sertleşme) nedir?", "Sert ünsüzle biten sözcüğe c, d, g ile başlayan ek gelince ç, t, k olur: kitapçı, sokakta, açtı."],
["Ünsüz yumuşaması nedir?", "p, ç, t, k ünlüyle başlayan ek alınca b, c, d, ğ olur: dolabı, ağacı, kanadı, çocuğu. Tek hecelilerde genelde olmaz."],
["Ünlü düşmesine 3 örnek", "ağız → ağzı, burun → burnu, oğul → oğlu"],
["Ünlü daralması hangi ekle olur?", "-yor ekiyle: başla → başlıyor, de → diyor, ye → yiyor"],
["Sıfat-fiil eklerinin kodu?", "ANASI MEZAR DIKECEKMIŞ → -an, -ası, -mez, -ar, -dik, -ecek, -miş"],
["İsim-fiil ekleri?", "-ma, -ış, -mak (okuma, gidiş, yazmak)"],
["Zarf-fiil ekleri?", "-ıp, -arak, -ınca, -ken, -dıkça, -madan, -alı, -r...-mez, -casına"],
["Belirtili nesne hangi soruyla bulunur?", "Yükleme “neyi, kimi?” sorulur; -ı/-i/-u/-ü eki alır."],
["Dolaylı tümleç hangi ekleri alır?", "-e (yönelme), -de (bulunma), -den (ayrılma): kime, nerede, nereden"],
["Kurum adlarına gelen ekler kesmeyle ayrılır mı?", "Hayır: Türk Dil Kurumunun. Kısaltmalarda ayrılır: TDK'nin."],
["Bitişik yazılan “ki”ler hangileri?", "belki, çünkü, sanki, oysaki, mademki, hâlbuki, meğerki"],
["“de/da” bağlacı nasıl yazılır?", "Her zaman ayrı. Çıkarınca anlam bozulmuyorsa bağlaçtır: “Ben de geldim.”"],
["İki nokta ne zaman kullanılır?", "Kendisinden sonra açıklama, örnek ya da alıntı gelecek cümlenin sonunda."],
["Tartışmacı anlatımın ipuçları?", "Karşı görüşü çürütme, okura soru sorma, kanıt sunma, ikna amacı."],
["Öznel ve nesnel yargı farkı?", "Nesnel: kanıtlanabilir. Öznel: kişiden kişiye değişir (“bence” eklenebilir)."],
["Girişik birleşik cümle nedir?", "İçinde fiilimsi grubu bulunan cümle: “Eve gelince haber ver.”"],
["“Yaklaşık yüz kadar kişi” neden yanlış?", "Gereksiz sözcük: “yaklaşık” ile “kadar” aynı anlamı verir."],
["Paragrafta ana düşünce nerede aranır?", "Genellikle ilk ya da son cümlede; “kısacası, bu yüzden, yani” sonrasında."]
],
mat: [
["1'den n'e kadar sayıların toplamı", "n(n+1)/2"],
["İlk n çift sayının toplamı", "n(n+1)"],
["İlk n tek sayının toplamı", "n²"],
["Terim sayısı formülü", "(son − ilk) / artış + 1"],
["3 ve 9 ile bölünebilme", "Rakamlar toplamı 3'ün / 9'un katı olmalı"],
["4 ile bölünebilme", "Son iki basamak 4'ün katı olmalı"],
["11 ile bölünebilme", "Sağdan sola +, −, +, − işaretleyip topla; sonuç 11'in katı olmalı"],
["Pozitif bölen sayısı", "a^x · b^y → (x+1)(y+1)"],
["EBOB ile EKOK ilişkisi", "İki sayı için EBOB · EKOK = a · b"],
["En küçük asal sayı", "2 (tek çift asal). 1 asal değildir."],
["(−2)⁴ ile −2⁴ farkı", "(−2)⁴ = 16, −2⁴ = −16"],
["%20 zam sonra %20 indirim", "1,2 × 0,8 = 0,96 → %4 azalır"],
["Kâr-zarar neye göre hesaplanır?", "Aksi söylenmedikçe alış (maliyet) fiyatına göre"],
["Birlikte iş: a ve b gün", "t = a·b / (a+b)"],
["Karşılaşma ve yetişme süresi", "Karşılaşma: yol/(v₁+v₂). Yetişme: aradaki mesafe/(v₁−v₂)"],
["Yaş problemlerinin altın kuralı", "İki kişinin yaş farkı hiç değişmez."],
["s(A ∪ B)", "s(A) + s(B) − s(A ∩ B)"],
["n elemanlı kümenin alt küme sayısı", "2ⁿ (öz alt küme: 2ⁿ − 1)"],
["Tekrarlı harf permütasyonu", "n! / (tekrarların faktöriyelleri çarpımı). KPSS → 4!/2! = 12"],
["Kombinasyon C(n, r)", "n! / (r! · (n−r)!)"],
["Çokgenin iç açıları toplamı", "(n − 2) · 180°"],
["Özel dik üçgenler", "3-4-5, 5-12-13, 8-15-17; 30-60-90: 1-√3-2; 45-45-90: 1-1-√2"],
["Daire alanı ve çevresi", "Alan πr², çevre 2πr"],
["KPSS net hesabı", "Net = Doğru − Yanlış/4 (4 yanlış 1 doğruyu götürür)"]
],
tar: [
["Türk adıyla kurulan ilk Türk devleti", "Göktürkler (552, Bumin Kağan)"],
["Orhun Yazıtları", "II. Göktürk (Kutluk) Devleti; Tonyukuk, Kül Tigin, Bilge Kağan. Türk adının geçtiği ilk Türk kaynağı."],
["Yerleşik hayata geçen ilk Türk devleti", "Uygurlar (Mani dini, kendi alfabesi, matbaa)"],
["Onlu sistem", "Asya Hun, Mete Han, M.Ö. 209"],
["Kavimler Göçü", "375; Hunların batıya ilerlemesi; Avrupa'da feodalitenin ve Orta Çağ'ın başlangıcı"],
["Talas Savaşı (751)", "Türk-Arap yakınlaşması; kâğıt İslam dünyasına geçti"],
["Kutadgu Bilig", "Yusuf Has Hacib, Karahanlılar"],
["Divanü Lügati't-Türk", "Kaşgarlı Mahmud; Araplara Türkçe öğretmek için"],
["Dandanakan (1040)", "Selçuklu-Gazneli; Büyük Selçuklu Devleti kuruldu"],
["Malazgirt (1071)", "Alparslan; Anadolu'nun kapıları Türklere açıldı"],
["Miryokefalon (1176)", "II. Kılıçarslan; Anadolu kesin Türk yurdu oldu"],
["Kösedağ (1243)", "Türkiye Selçukluları Moğol egemenliğine girdi"],
["Ankara Savaşı (1402)", "Timur – Yıldırım Bayezid; Fetret Devri"],
["Zitvatorok (1606)", "Avusturya ile eşitlik; Osmanlı üstünlüğü sona erdi"],
["Karlofça (1699)", "İlk büyük toprak kaybı"],
["Küçük Kaynarca (1774)", "Kırım bağımsız; Rusya Ortodoksların hamisi; ilk savaş tazminatı"],
["Divan-ı Hümayun görev dağılımı", "Defterdar: maliye. Kazasker: hukuk-eğitim. Nişancı: tuğra-tapu."],
["Tımar / zeamet / has", "3.000–20.000 / 20.000–100.000 / 100.000+ akçe"],
["İlk Türk matbaası", "İbrahim Müteferrika, 1727, Lale Devri"],
["Amasya Genelgesi (22 Haziran 1919)", "“Milletin istiklalini yine milletin azim ve kararı kurtaracaktır.”"],
["Erzurum Kongresi", "Toplanışı bölgesel, kararları ulusal; manda ve himaye ilk kez reddedildi"],
["Sivas Kongresi", "Cemiyetler Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti adıyla birleşti"],
["Misak-ı Milli (28 Ocak 1920)", "Son Osmanlı Mebusan Meclisi kabul etti"],
["Gümrü Antlaşması (3 Aralık 1920)", "Ermenistan ile; TBMM'nin ilk askerî-siyasi başarısı ve ilk uluslararası antlaşması"],
["Moskova Antlaşması (16 Mart 1921)", "Sovyet Rusya ile; Misak-ı Milli'yi tanıyan ilk büyük devlet"],
["Ankara Antlaşması (20 Ekim 1921)", "Fransa ile; bir İtilaf devleti TBMM'yi tanıdı"],
["Sakarya Meydan Muharebesi", "23 Ağustos – 13 Eylül 1921; Gazi unvanı ve Mareşal rütbesi"],
["Mudanya Ateşkesi (11 Ekim 1922)", "Doğu Trakya ve İstanbul savaşmadan alındı"],
["3 Mart 1924'te neler oldu?", "Halifelik kaldırıldı, Tevhid-i Tedrisat, Şer'iye ve Evkaf ile Erkân-ı Harbiye Vekâletleri kaldırıldı"],
["Kadınlara siyasi haklar", "Belediye 1930, muhtarlık 1933, milletvekilliği 5 Aralık 1934"],
["Atatürk ilkelerinin anayasaya girişi", "1937"],
["Balkan Antantı / Sadabat Paktı", "1934: Türkiye, Yunanistan, Yugoslavya, Romanya / 1937: Türkiye, İran, Irak, Afganistan"],
["Montrö Boğazlar Sözleşmesi", "1936; Boğazlarda tam Türk egemenliği"],
["Hatay'ın anavatana katılışı", "29 Haziran 1939"],
["Asya Hun hükümdar unvanı", "Tanhu"],
["“Sultan” unvanını ilk kullanan", "Gazneli Mahmut"],
["Başkent İznik'ten Konya'ya", "I. Haçlı Seferi sonrası, Türkiye Selçukluları"],
["İlk Osmanlı tersanesi", "Karamürsel (Orhan Bey)"],
["Halifelik Osmanlı'ya ne zaman geçti?", "1517 Ridaniye, Yavuz Sultan Selim"],
["Vaka-i Hayriye", "1826, II. Mahmut; Yeniçeri Ocağı kaldırıldı"],
["İlk dış borç / Düyun-ı Umumiye", "1854 Kırım Savaşı / 1881"],
["Havza Genelgesi (28 Mayıs 1919)", "İşgallere karşı protesto mitingleri"],
["İstiklal Marşı", "12 Mart 1921, Mehmet Akif Ersoy"],
["Kars Antlaşması (13 Ekim 1921)", "Kafkas cumhuriyetleriyle; doğu sınırı kesinleşti"],
["Lozan'da çözülemeyen konu", "Irak sınırı (Musul) → 1926 Ankara Antlaşması, İngiltere"],
["Ankara başkent oldu", "13 Ekim 1923"],
["Çok partili hayat denemeleri", "Terakkiperver Cumhuriyet Fırkası 1924 (Şeyh Said İsyanı sonrası kapatıldı), Serbest Cumhuriyet Fırkası 1930 (Ali Fethi Okyar)"],
["Devletçiliğe geçişin nedeni", "1929 Dünya Ekonomik Bunalımı; I. Beş Yıllık Sanayi Planı 1934"],
["Medeni Kanun / Ceza Kanunu kaynağı", "İsviçre / İtalya"]
],
cog: [
["Türkiye'nin enlem ve boylam aralığı", "36°–42° Kuzey enlemleri, 26°–45° Doğu boylamları"],
["Doğu–batı yerel saat farkı", "19 boylam × 4 dk = 76 dakika"],
["Kıyı tipleri", "Boyuna: Karadeniz, Akdeniz. Enine: Ege. Ria: İstanbul Boğazı, Haliç."],
["Akdeniz ikliminin bitki örtüsü", "Maki"],
["Karasal iklimin bitki örtüsü", "Bozkır (step)"],
["Kırkikindi yağmurları", "İç Anadolu, ilkbahar; konveksiyonel (yükselim) yağış"],
["Heyelan set gölleri", "Tortum, Abant, Yedigöller, Sera"],
["Van Gölü nasıl oluştu?", "Volkanik set gölü: Nemrut'un lavları önünü kapattı"],
["Karstik şekiller", "Obruk, dolin, uvala, polye, mağara, traverten (Pamukkale)"],
["Bor nerede çıkarılır?", "Eskişehir Kırka, Balıkesir Bigadiç, Kütahya Emet, Bursa Kestelek"],
["Krom nerede çıkarılır?", "Elazığ Guleman, Muğla Fethiye, Bursa Orhaneli"],
["Demir nerede çıkarılır?", "Sivas Divriği, Malatya Hekimhan"],
["Bakır nerede çıkarılır?", "Artvin Murgul, Kastamonu Küre, Elazığ Maden, Rize Çayeli"],
["Boksit (alüminyum)", "Konya Seydişehir"],
["Linyit havzaları", "Afşin-Elbistan, Soma, Tunçbilek-Seyitömer, Yatağan"],
["Taşkömürü", "Zonguldak"],
["Petrol sahaları", "Batman (Raman), Adıyaman, Şırnak (Gabar)"],
["İlk jeotermal santral", "Denizli Sarayköy (Kızıldere)"],
["GAP illerinin kodu", "SiBAŞŞ MaGaKiDi: Siirt, Batman, Adıyaman, Şanlıurfa, Şırnak, Mardin, Gaziantep, Kilis, Diyarbakır"],
["Çay / fındık / muz", "Rize / Ordu, Giresun / Anamur, Alanya"],
["Pamuk nerede yetişir?", "Şanlıurfa (Harran), Çukurova, Söke"],
["En büyük ve en küçük bölge", "Doğu Anadolu / Güneydoğu Anadolu"],
["En yüksek dağ", "Ağrı Dağı, 5137 m (volkanik)"],
["Sınırlarımız içindeki en uzun akarsu", "Kızılırmak"],
["İlk nüfus sayımı", "1927, yaklaşık 13,6 milyon"],
["En büyük göl", "Van Gölü (ikinci Tuz Gölü)"],
["Fırat ve Dicle nereye dökülür?", "Basra Körfezi"],
["En çok ve en az yağış", "Rize / Tuz Gölü çevresi"],
["Yıllık sıcaklık farkı en fazla / en az", "Doğu Anadolu / Karadeniz kıyıları"],
["En yaygın iklim tipi", "Karasal iklim"],
["Heyelanın en sık görüldüğü bölge", "Karadeniz"],
["Peribacaları", "Volkanik tüfün aşınması; Nevşehir (Kapadokya)"],
["Karabük demir-çelik neden orada?", "Zonguldak taşkömürüne yakınlık (demir Divriği'den gelir)"],
["Petrol rafinerileri", "İzmit (Kocaeli), Aliağa (İzmir), Kırıkkale, Batman"],
["Rüzgâr enerjisi", "Ege ve Marmara (İzmir, Balıkesir, Çanakkale)"],
["Fırat üzerindeki barajlar", "Atatürk, Keban, Karakaya (Dicle üzerinde Ilısu)"],
["Kuzey Anadolu Fay Hattı", "Marmara'dan Doğu Anadolu'ya uzanan en önemli fay hattı"],
["Meriç", "Türkiye-Yunanistan sınırının büyük bölümü"],
["Nüfus yoğunluğu en fazla / en az", "Marmara / Doğu Anadolu"]
],
vat: [
["Değiştirilemez maddeler", "1: Devletin şekli Cumhuriyet. 2: Cumhuriyetin nitelikleri. 3: Bütünlük, dil, bayrak, marş, başkent. m.4 bunları korur."],
["TBMM'nin yapısı", "600 milletvekili, 5 yılda bir seçim, 18 yaş seçilme"],
["Toplantı ve karar yeter sayısı", "Toplantı: 200 (1/3). Karar: katılanların salt çoğunluğu, en az 151."],
["Anayasa değişikliği oyları", "Teklif 200. 360–399: halkoylaması zorunlu. 400+: CB isterse halkoyuna sunar."],
["Cumhurbaşkanlığı şartları", "40 yaş, yükseköğrenim, milletvekili seçilme yeterliliği; 5 yıl, en fazla 2 dönem"],
["CB adayını kim gösterebilir?", "Parti grupları, son seçimde en az %5 oy alan partiler, 100.000 seçmen"],
["Anayasa Mahkemesi", "15 üye: 12 CB, 3 TBMM; 12 yıl, bir kez; Yüce Divan sıfatıyla yargılar"],
["HSK", "13 üye; Başkan Adalet Bakanı, Bakan Yardımcısı tabii üye; 4 CB, 7 TBMM; 4 yıl"],
["İlk yazılı anayasa", "Kanun-i Esasi, 23 Aralık 1876"],
["1921 Teşkilat-ı Esasiye", "Güçler birliği, millî egemenlik; temel haklara yer vermedi"],
["1961 Anayasası'nın yenilikleri", "Anayasa Mahkemesi, çift meclis, sosyal devlet, geniş temel haklar"],
["Hak ehliyeti ne zaman başlar?", "Sağ doğmak koşuluyla ana rahmine düşülen andan"],
["Fiil ehliyetinin koşulları", "Ayırt etme gücü, ergin olma, kısıtlı olmama"],
["Erginlik yolları", "18 yaş; evlenme; 15 yaşını dolduranın mahkeme kararıyla ergin kılınması"],
["Hukukun kaynakları", "Yazılı: Anayasa, kanun, CBK, yönetmelik. Yazısız: örf-adet. Yardımcı: içtihat, doktrin."],
["OHAL'de dokunulamayan haklar", "Yaşam hakkı, maddi-manevi bütünlük, din-vicdan özgürlüğü, suç ve cezaların geriye yürümezliği, masumiyet karinesi"],
["Kişi, sosyal ve siyasi haklar", "Kişi: negatif statü. Sosyal-ekonomik: pozitif statü. Siyasi: aktif statü."],
["Yerinden yönetim kuruluşları", "Yer bakımından: il özel idaresi, belediye, köy. Hizmet bakımından: üniversiteler, TRT."],
["Sayıştay", "Kamu harcamalarını TBMM adına denetler"],
["Olağanüstü hal", "CB ilan eder, en fazla 6 ay; TBMM onayı gerekir"],
["CB kararnamesiyle düzenlenemeyenler", "Temel haklar, kişi hakları ve siyasi haklar; kanunda açıkça düzenlenen konular"],
["CB hakkında soruşturma oyları", "Önerge 301, soruşturma açılması 360, Yüce Divan'a sevk 400"],
["Kanunu yayımlama süresi", "CB 15 gün içinde yayımlar ya da bir kez daha görüşülmek üzere geri gönderir"],
["Kanun teklifini kim verir?", "Yalnızca milletvekilleri (2017'den beri)"],
["Bütçe teklifini TBMM'ye kim sunar?", "Cumhurbaşkanı, mali yılbaşından en az 75 gün önce"],
["Danıştay / Yargıtay", "İdari yargının / adli yargının son inceleme mercii"],
["Uyuşmazlık Mahkemesi", "Adli ve idari yargı arasındaki görev ve hüküm uyuşmazlıkları"],
["Parti kapatma", "Davayı Yargıtay Cumhuriyet Başsavcısı açar, kararı Anayasa Mahkemesi verir"],
["Bireysel başvuru", "Temel hakkı kamu gücünce ihlal edilen kişi Anayasa Mahkemesi'ne başvurur (2012'den beri)"],
["YSK'nın görevi", "Seçimlerin genel yönetim ve denetimi; kararları kesindir"],
["Kamu Denetçiliği Kurumu", "Ombudsman; TBMM Başkanlığına bağlı"],
["Belediye organları", "Belediye meclisi, belediye encümeni, belediye başkanı"],
["Özel hukuk ve kamu hukuku", "Özel: medeni, borçlar, ticaret. Kamu: anayasa, idare, ceza, vergi."],
["Bakan olan milletvekili", "TBMM üyeliği sona erer (m.106)"],
["Valiyi kim atar?", "Cumhurbaşkanı"]
],
gun: [
["Türk Devletleri Teşkilatı tam üyeleri", "Türkiye, Azerbaycan, Kazakistan, Kırgızistan, Özbekistan. Gözlemci: Macaristan, Türkmenistan, KKTC."],
["Türkiye'nin NATO üyeliği", "1952 (Yunanistan ile birlikte)"],
["NATO'ya son katılanlar", "Finlandiya 2023, İsveç 2024 → 32 üye"],
["Türksat 6A", "İlk yerli ve millî haberleşme uydusu; Temmuz 2024"],
["1915 Çanakkale Köprüsü", "18 Mart 2022; dünyanın en uzun orta açıklıklı asma köprüsü (2023 m)"],
["Sakarya Gaz Sahası", "Karadeniz; 2020 keşif, 2023 ilk gaz (Filyos)"],
["Akkuyu NGS", "Mersin; Türkiye'nin ilk nükleer santrali"],
["UNESCO 2023'te eklenenler", "Gordion ve Anadolu'nun Orta Çağ ahşap hipostil camileri"],
["Göbeklitepe / Arslantepe", "Şanlıurfa, UNESCO 2018 / Malatya, UNESCO 2021"],
["İslam İşbirliği Teşkilatı", "57 üye, merkezi Cidde"]
],
eb: [
["Piaget'in dönemleri", "Duyusal-motor (0–2), İşlem öncesi (2–7), Somut işlemler (7–11), Soyut işlemler (11+)"],
["Nesne sürekliliği hangi dönemde?", "Duyusal-motor"],
["Korunum hangi dönemde?", "Somut işlemler"],
["Benmerkezcilik ve animizm", "İşlem öncesi dönem"],
["Erikson: ergenlik krizi", "Kimlik kazanmaya karşı rol karmaşası"],
["Kohlberg'in düzeyleri", "Gelenek öncesi, geleneksel, gelenek sonrası"],
["Olumsuz pekiştirme", "Hoşa gitmeyen uyaranı kaldırarak davranışı artırma. Ceza değildir."],
["Sönmeye en dirençli tarife", "Değişken oranlı (kumar makinesi)"],
["Bandura", "Sosyal bilişsel öğrenme: model alma, dolaylı pekiştirme, öz yeterlik"],
["Ausubel", "Sunuş yoluyla öğretim, ön örgütleyiciler, tümdengelim"],
["Bruner", "Buluş yoluyla öğretim, tümevarım, sarmal program"],
["Vygotsky", "Yakınsal gelişim alanı, iskele kurma"],
["Gardner", "Çoklu zekâ kuramı"],
["Geçerlik ve güvenirlik", "Geçerlik: ölçmek istediğini ölçme. Güvenirlik: tutarlılık. Güvenirlik geçerliğin ön koşuludur."],
["Ölçek türleri", "Sınıflama, sıralama, eşit aralıklı, oranlı (yalnız oranlıda mutlak sıfır var)"],
["Tyler modelinin öğeleri", "Hedef, içerik, eğitim durumları, sınama durumları"],
["Revize Bloom basamakları", "Hatırlama, anlama, uygulama, çözümleme, değerlendirme, yaratma"],
["Rehberliğin çekirdek hizmeti", "Psikolojik danışma"]
]
};
